// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using alina_backend;

#nullable disable

namespace alina_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260217074409_AddCustomOfferIdToMedia")]
    partial class AddCustomOfferIdToMedia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("alina_backend.app.dashboard.AchievementBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("GoalType")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("AchievementBadges");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AchievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AchievementBadge")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAchieved")
                        .HasColumnType("boolean");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ProgressPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.GoalProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("GoalProgress");
                });

            modelBuilder.Entity("alina_backend.app.disputes.Dispute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OpenedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("Resolution")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ResolutionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Disputes");
                });

            modelBuilder.Entity("alina_backend.app.finance.CurrencyRate", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Code");

                    b.ToTable("CurrencyRates");

                    b.HasData(
                        new
                        {
                            Code = "USD",
                            LastUpdated = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(5890),
                            Rate = 1.0000m
                        },
                        new
                        {
                            Code = "SAR",
                            LastUpdated = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(5890),
                            Rate = 3.7500m
                        },
                        new
                        {
                            Code = "AED",
                            LastUpdated = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(5890),
                            Rate = 3.6725m
                        },
                        new
                        {
                            Code = "JOD",
                            LastUpdated = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(5890),
                            Rate = 0.7090m
                        },
                        new
                        {
                            Code = "KWD",
                            LastUpdated = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(5890),
                            Rate = 0.3070m
                        },
                        new
                        {
                            Code = "BHD",
                            LastUpdated = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(5890),
                            Rate = 0.3760m
                        },
                        new
                        {
                            Code = "OMR",
                            LastUpdated = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(5890),
                            Rate = 0.3845m
                        });
                });

            modelBuilder.Entity("alina_backend.app.finance.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("alina_backend.app.finance.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvailableBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EscrowBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PendingWithdrawal")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("alina_backend.app.finance.WithdrawalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankDetails")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WithdrawalRequests");
                });

            modelBuilder.Entity("alina_backend.app.fraud.FraudFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("SeverityScore")
                        .HasColumnType("numeric");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FraudFlags");
                });

            modelBuilder.Entity("alina_backend.app.legal.LegalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LegalDocuments");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2698ce91-4358-47da-a35a-27ade6438847"),
                            CreatedAt = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(6370),
                            Icon = "brush",
                            Name = "Graphics & Design",
                            NameAr = "الجرافيك والتصميم"
                        },
                        new
                        {
                            Id = new Guid("d990efbe-11db-4864-b89d-8e40998cd99f"),
                            CreatedAt = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(6370),
                            Icon = "code",
                            Name = "Programming & Tech",
                            NameAr = "البرمجة والتكنولوجيا"
                        },
                        new
                        {
                            Id = new Guid("ee112f02-7c1d-4203-9441-54d0bd6e12f1"),
                            CreatedAt = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(6380),
                            Icon = "pen",
                            Name = "Writing & Translation",
                            NameAr = "الكتابة والترجمة"
                        },
                        new
                        {
                            Id = new Guid("c7285295-07bb-46f4-94cb-48d3f546bae8"),
                            CreatedAt = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(6380),
                            Icon = "video",
                            Name = "Video & Animation",
                            NameAr = "الفيديو والأنيميشن"
                        },
                        new
                        {
                            Id = new Guid("798ca124-8291-4f5c-8a06-1c2dc53f271e"),
                            CreatedAt = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(6380),
                            Icon = "home",
                            Name = "Home Services",
                            NameAr = "خدمات المنزل"
                        },
                        new
                        {
                            Id = new Guid("3eb51053-5c8f-4873-88b0-f94139f1d4bb"),
                            CreatedAt = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(6390),
                            Name = "Logo Design",
                            NameAr = "تصميم الشعارات",
                            ParentId = new Guid("2698ce91-4358-47da-a35a-27ade6438847")
                        },
                        new
                        {
                            Id = new Guid("d4b0eb04-5117-4e62-a882-f348a4c280f5"),
                            CreatedAt = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(6390),
                            Name = "Web Design",
                            NameAr = "تصميم المواقع",
                            ParentId = new Guid("2698ce91-4358-47da-a35a-27ade6438847")
                        },
                        new
                        {
                            Id = new Guid("780f7b68-8caf-4a72-93c7-c67e326fa58b"),
                            CreatedAt = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(6400),
                            Name = "Brand Identity",
                            NameAr = "هوية العلامة التجارية",
                            ParentId = new Guid("2698ce91-4358-47da-a35a-27ade6438847")
                        },
                        new
                        {
                            Id = new Guid("df6f2b80-2761-4197-9374-85e1b61a751f"),
                            CreatedAt = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(6410),
                            Name = "Web Development",
                            NameAr = "تطوير المواقع",
                            ParentId = new Guid("d990efbe-11db-4864-b89d-8e40998cd99f")
                        },
                        new
                        {
                            Id = new Guid("f7cc3e16-00a1-427d-a1c2-bcd47c7eac66"),
                            CreatedAt = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(6410),
                            Name = "Mobile Apps",
                            NameAr = "تطبيقات الجوال",
                            ParentId = new Guid("d990efbe-11db-4864-b89d-8e40998cd99f")
                        },
                        new
                        {
                            Id = new Guid("ed70ae7f-b3ae-452f-bf3d-a1267c7e0041"),
                            CreatedAt = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(6420),
                            Name = "AI Services",
                            NameAr = "خدمات الذكاء الاصطناعي",
                            ParentId = new Guid("d990efbe-11db-4864-b89d-8e40998cd99f")
                        },
                        new
                        {
                            Id = new Guid("b39df55e-0500-4a84-8d61-864cbdb24ffc"),
                            CreatedAt = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(6430),
                            Name = "Cleaning",
                            NameAr = "التنظيف",
                            ParentId = new Guid("798ca124-8291-4f5c-8a06-1c2dc53f271e")
                        },
                        new
                        {
                            Id = new Guid("68902e55-4bbd-42cb-86a1-8ead3a9bd18d"),
                            CreatedAt = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(6430),
                            Name = "Handyman",
                            NameAr = "أعمال الصيانة",
                            ParentId = new Guid("798ca124-8291-4f5c-8a06-1c2dc53f271e")
                        },
                        new
                        {
                            Id = new Guid("6b8887de-3519-48b4-91ba-61e9b894ef2f"),
                            CreatedAt = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(6440),
                            Name = "Moving",
                            NameAr = "نقل الأثاث",
                            ParentId = new Guid("798ca124-8291-4f5c-8a06-1c2dc53f271e")
                        },
                        new
                        {
                            Id = new Guid("66360125-3e54-4d34-bfe7-2d13a700b9f8"),
                            CreatedAt = new DateTime(2026, 2, 17, 7, 44, 9, 320, DateTimeKind.Utc).AddTicks(6450),
                            Name = "Gardening",
                            NameAr = "تنسيق الحدائق",
                            ParentId = new Guid("798ca124-8291-4f5c-8a06-1c2dc53f271e")
                        });
                });

            modelBuilder.Entity("alina_backend.app.marketplace.CustomOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attachments")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("DeliveryTimeInDays")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("CustomOffers");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GigId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GigId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GigId1");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Gig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeliveryTimeInDays")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MainImage")
                        .HasColumnType("text");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.ToTable("Gigs");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("TaskerId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<List<string>>("AttachmentUrls")
                        .HasColumnType("text[]");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CommissionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryMessage")
                        .HasColumnType("text");

                    b.Property<Guid?>("GigId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PlatformFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PlatformFeePercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<decimal?>("SellerAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("GigId");

                    b.HasIndex("OfferId")
                        .IsUnique();

                    b.HasIndex("SellerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeliveryTimeInDays")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GigId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GigId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("RevieweeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("RevieweeId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.SearchAnalytics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FirstSearchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSearchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SearchCount")
                        .HasColumnType("integer");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SearchAnalytics");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.UserTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedTaskerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<Guid>("PosterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTaskerId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PosterId");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("alina_backend.app.media.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomOfferId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("GigId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GigId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("UserTaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserTaskId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.HasIndex("GigId1");

                    b.HasIndex("OwnerId");

                    b.HasIndex("UserTaskId");

                    b.HasIndex("UserTaskId1");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("alina_backend.app.messaging.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("alina_backend.app.notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("alina_backend.app.notifications.UserNotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MarketingEmails")
                        .HasColumnType("boolean");

                    b.Property<bool>("MessageNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("OfferNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("OrderUpdates")
                        .HasColumnType("boolean");

                    b.Property<bool>("PushEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotificationSettings");
                });

            modelBuilder.Entity("alina_backend.app.orders.Revision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attachments")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequesterId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RequesterId1")
                        .HasColumnType("uuid");

                    b.Property<string>("ResolutionAttachments")
                        .HasColumnType("text");

                    b.Property<string>("ResolutionMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId1");

                    b.ToTable("Revisions");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("72b3ee9c-fcb2-411b-afea-2b666b232642"),
                            Code = "en",
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("ac290777-27da-40bc-b100-b693f0a199e0"),
                            Code = "ar",
                            Name = "Arabic"
                        },
                        new
                        {
                            Id = new Guid("0cd400d4-953c-4d78-852d-1fd0711eea36"),
                            Code = "es",
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = new Guid("3f03ce3d-a75e-450a-b702-ae0f6c2195a2"),
                            Code = "fr",
                            Name = "French"
                        },
                        new
                        {
                            Id = new Guid("82c80b94-12f8-4695-b345-ae947f2a676c"),
                            Code = "de",
                            Name = "German"
                        },
                        new
                        {
                            Id = new Guid("729e6a81-a475-4c01-8898-cb31f2ba42d7"),
                            Code = "zh",
                            Name = "Chinese"
                        },
                        new
                        {
                            Id = new Guid("5674634a-3a02-4572-b7d2-e244a21726f4"),
                            Code = "ja",
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = new Guid("332b5229-629f-46f1-80d6-81084d502f3c"),
                            Code = "pt",
                            Name = "Portuguese"
                        },
                        new
                        {
                            Id = new Guid("da246ef2-a634-4c13-bb60-f5118050a935"),
                            Code = "ru",
                            Name = "Russian"
                        },
                        new
                        {
                            Id = new Guid("155ed8cd-a8be-425b-96e0-ff456053eb49"),
                            Code = "hi",
                            Name = "Hindi"
                        });
                });

            modelBuilder.Entity("alina_backend.app.profiles.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GithubUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastDeliveryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PreferredCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("ProfileCompletionPercentage")
                        .HasColumnType("integer");

                    b.Property<int?>("ResponseTimeHours")
                        .HasColumnType("integer");

                    b.Property<int>("SellerLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Tagline")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TwitterUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("alina_backend.app.profiles.ProfileLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProficiencyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileLanguages");
                });

            modelBuilder.Entity("alina_backend.app.profiles.ProfileSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProfileSkills");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7477f04-1a64-4a6d-ba70-2b9af38b4974"),
                            CategoryName = "Programming",
                            Name = "React"
                        },
                        new
                        {
                            Id = new Guid("9002d604-e751-4257-8b7a-feca685c0ad4"),
                            CategoryName = "Programming",
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = new Guid("020d79f6-cedc-48d2-ba76-2c8c1e68d2f9"),
                            CategoryName = "Programming",
                            Name = "Python"
                        },
                        new
                        {
                            Id = new Guid("2426b1fa-39f8-4d0b-b65f-72764c744a0c"),
                            CategoryName = "Programming",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("f3c4aff4-5063-4f08-872c-686e7e3323e6"),
                            CategoryName = "Programming",
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = new Guid("99b3dd6a-fa29-4ae5-805a-34a4267b6308"),
                            CategoryName = "Programming",
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("38d56d07-7d21-4097-addc-65086878d75a"),
                            CategoryName = "Programming",
                            Name = "Java"
                        },
                        new
                        {
                            Id = new Guid("e384b962-34e9-43fd-848e-5de19942714a"),
                            CategoryName = "Programming",
                            Name = "Flutter"
                        },
                        new
                        {
                            Id = new Guid("9acfb071-d35a-464d-b579-3ecaaffcc8b3"),
                            CategoryName = "Programming",
                            Name = "Swift"
                        },
                        new
                        {
                            Id = new Guid("3e915f64-0d66-4003-83e0-f3bfceaf4a9f"),
                            CategoryName = "Programming",
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = new Guid("d1064750-b9ff-4797-875f-8debf9abf3ed"),
                            CategoryName = "Design",
                            Name = "UI/UX Design"
                        },
                        new
                        {
                            Id = new Guid("90d2283d-29b0-4d32-88cb-3fc364f7ca76"),
                            CategoryName = "Design",
                            Name = "Figma"
                        },
                        new
                        {
                            Id = new Guid("8efb53f4-ca7a-42b2-8e96-9d2cc9644db7"),
                            CategoryName = "Design",
                            Name = "Adobe Photoshop"
                        },
                        new
                        {
                            Id = new Guid("4dceeb7b-861f-4545-9c2a-13db37eed448"),
                            CategoryName = "Design",
                            Name = "Adobe Illustrator"
                        },
                        new
                        {
                            Id = new Guid("9ab06298-86ce-4feb-a714-f5846e2155dd"),
                            CategoryName = "Design",
                            Name = "Graphic Design"
                        },
                        new
                        {
                            Id = new Guid("2ac02d0f-0df5-4b53-9641-8e267477bb95"),
                            CategoryName = "Design",
                            Name = "Logo Design"
                        },
                        new
                        {
                            Id = new Guid("4dfb0e14-16d5-451e-a429-6d84bd6101fe"),
                            CategoryName = "Design",
                            Name = "3D Modeling"
                        },
                        new
                        {
                            Id = new Guid("a6908d44-4585-4479-b50b-5567787e5dd3"),
                            CategoryName = "Marketing",
                            Name = "SEO"
                        },
                        new
                        {
                            Id = new Guid("8c260b7e-b68b-4654-a33a-b74d8994249a"),
                            CategoryName = "Marketing",
                            Name = "Social Media Marketing"
                        },
                        new
                        {
                            Id = new Guid("6401e11d-6ae1-495a-bc57-95fdc11d2a7d"),
                            CategoryName = "Marketing",
                            Name = "Content Writing"
                        },
                        new
                        {
                            Id = new Guid("440ee410-eee8-4eb7-b14a-36148735f955"),
                            CategoryName = "Marketing",
                            Name = "Email Marketing"
                        },
                        new
                        {
                            Id = new Guid("311f12f1-312e-48db-93ed-699410d18425"),
                            CategoryName = "Marketing",
                            Name = "Digital Marketing"
                        },
                        new
                        {
                            Id = new Guid("c6916a7f-08f9-485e-9712-f022e21e5572"),
                            CategoryName = "Video & Animation",
                            Name = "Video Editing"
                        },
                        new
                        {
                            Id = new Guid("28897e2c-e197-48f3-b345-4eaa1062692a"),
                            CategoryName = "Video & Animation",
                            Name = "After Effects"
                        },
                        new
                        {
                            Id = new Guid("4fad995f-a21e-4f85-a23e-9e0cf3be2994"),
                            CategoryName = "Video & Animation",
                            Name = "Animation"
                        },
                        new
                        {
                            Id = new Guid("4b087ef6-d768-406c-b93a-53c7d259ca4d"),
                            CategoryName = "Writing",
                            Name = "Copywriting"
                        },
                        new
                        {
                            Id = new Guid("1bb0f897-4872-422e-97f6-83627107897e"),
                            CategoryName = "Writing",
                            Name = "Technical Writing"
                        },
                        new
                        {
                            Id = new Guid("1b85d865-8ae9-4139-9955-5227a07a8e4c"),
                            CategoryName = "Writing",
                            Name = "Translation"
                        },
                        new
                        {
                            Id = new Guid("36c3a59c-e03b-4d52-8a94-eca9bd76538e"),
                            CategoryName = "Business",
                            Name = "Data Analysis"
                        },
                        new
                        {
                            Id = new Guid("1daa2649-ad98-44fa-8235-c8c1a160f45a"),
                            CategoryName = "Business",
                            Name = "Business Consulting"
                        });
                });

            modelBuilder.Entity("alina_backend.app.support.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("alina_backend.app.users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("alina_backend.app.users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.Goal", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.GoalProgress", b =>
                {
                    b.HasOne("alina_backend.app.dashboard.Goal", "Goal")
                        .WithMany("ProgressEntries")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("alina_backend.app.disputes.Dispute", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("alina_backend.app.finance.Transaction", b =>
                {
                    b.HasOne("alina_backend.app.finance.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("alina_backend.app.finance.Wallet", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Profile")
                        .WithOne()
                        .HasForeignKey("alina_backend.app.finance.Wallet", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("alina_backend.app.finance.WithdrawalRequest", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.fraud.FraudFlag", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Category", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Category", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.CustomOffer", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.users.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Favorite", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Gig", "Gig")
                        .WithMany()
                        .HasForeignKey("GigId1");

                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Gig", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Category", "Category")
                        .WithMany("Gigs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Offer", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.UserTask", "Task")
                        .WithMany("Offers")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Tasker")
                        .WithMany()
                        .HasForeignKey("TaskerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("Tasker");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Order", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("alina_backend.app.marketplace.Gig", "Gig")
                        .WithMany()
                        .HasForeignKey("GigId");

                    b.HasOne("alina_backend.app.marketplace.Offer", "Offer")
                        .WithOne()
                        .HasForeignKey("alina_backend.app.marketplace.Order", "OfferId");

                    b.HasOne("alina_backend.app.profiles.Profile", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Gig");

                    b.Navigation("Offer");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Package", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Gig", "Gig")
                        .WithMany("Packages")
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Review", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Gig", "Gig")
                        .WithMany("Reviews")
                        .HasForeignKey("GigId");

                    b.HasOne("alina_backend.app.marketplace.Order", "Order")
                        .WithOne()
                        .HasForeignKey("alina_backend.app.marketplace.Review", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Reviewee")
                        .WithMany()
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");

                    b.Navigation("Order");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.SearchAnalytics", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.UserTask", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "AssignedTasker")
                        .WithMany()
                        .HasForeignKey("AssignedTaskerId");

                    b.HasOne("alina_backend.app.marketplace.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Poster")
                        .WithMany()
                        .HasForeignKey("PosterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTasker");

                    b.Navigation("Category");

                    b.Navigation("Poster");
                });

            modelBuilder.Entity("alina_backend.app.media.Media", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Gig", null)
                        .WithMany()
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("alina_backend.app.marketplace.Gig", null)
                        .WithMany("Gallery")
                        .HasForeignKey("GigId1");

                    b.HasOne("alina_backend.app.profiles.Profile", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.HasOne("alina_backend.app.marketplace.UserTask", null)
                        .WithMany()
                        .HasForeignKey("UserTaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("alina_backend.app.marketplace.UserTask", null)
                        .WithMany("Attachments")
                        .HasForeignKey("UserTaskId1");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("alina_backend.app.messaging.Message", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("alina_backend.app.notifications.Notification", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.notifications.UserNotificationSettings", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.orders.Revision", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId1");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Profile", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithOne()
                        .HasForeignKey("alina_backend.app.profiles.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.profiles.ProfileLanguage", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Language", "Language")
                        .WithMany("ProfileLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Profile")
                        .WithMany("ProfileLanguages")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("alina_backend.app.profiles.ProfileSkill", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Profile")
                        .WithMany("ProfileSkills")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Skill", "Skill")
                        .WithMany("ProfileSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("alina_backend.app.support.SupportTicket", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.users.RefreshToken", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.Goal", b =>
                {
                    b.Navigation("ProgressEntries");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Category", b =>
                {
                    b.Navigation("Gigs");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Gig", b =>
                {
                    b.Navigation("Gallery");

                    b.Navigation("Packages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.UserTask", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Language", b =>
                {
                    b.Navigation("ProfileLanguages");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Profile", b =>
                {
                    b.Navigation("ProfileLanguages");

                    b.Navigation("ProfileSkills");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Skill", b =>
                {
                    b.Navigation("ProfileSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
