// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using alina_backend;

#nullable disable

namespace alina_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260216131535_AddDeliveryFieldsToOrder")]
    partial class AddDeliveryFieldsToOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("alina_backend.app.dashboard.AchievementBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("GoalType")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("AchievementBadges");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AchievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AchievementBadge")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAchieved")
                        .HasColumnType("boolean");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ProgressPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.GoalProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("GoalProgress");
                });

            modelBuilder.Entity("alina_backend.app.disputes.Dispute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OpenedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("Resolution")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ResolutionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Disputes");
                });

            modelBuilder.Entity("alina_backend.app.finance.CurrencyRate", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Code");

                    b.ToTable("CurrencyRates");

                    b.HasData(
                        new
                        {
                            Code = "USD",
                            LastUpdated = new DateTime(2026, 2, 16, 13, 15, 34, 473, DateTimeKind.Utc).AddTicks(9960),
                            Rate = 1.0000m
                        },
                        new
                        {
                            Code = "SAR",
                            LastUpdated = new DateTime(2026, 2, 16, 13, 15, 34, 473, DateTimeKind.Utc).AddTicks(9960),
                            Rate = 3.7500m
                        },
                        new
                        {
                            Code = "AED",
                            LastUpdated = new DateTime(2026, 2, 16, 13, 15, 34, 473, DateTimeKind.Utc).AddTicks(9960),
                            Rate = 3.6725m
                        },
                        new
                        {
                            Code = "JOD",
                            LastUpdated = new DateTime(2026, 2, 16, 13, 15, 34, 473, DateTimeKind.Utc).AddTicks(9970),
                            Rate = 0.7090m
                        },
                        new
                        {
                            Code = "KWD",
                            LastUpdated = new DateTime(2026, 2, 16, 13, 15, 34, 473, DateTimeKind.Utc).AddTicks(9970),
                            Rate = 0.3070m
                        },
                        new
                        {
                            Code = "BHD",
                            LastUpdated = new DateTime(2026, 2, 16, 13, 15, 34, 473, DateTimeKind.Utc).AddTicks(9970),
                            Rate = 0.3760m
                        },
                        new
                        {
                            Code = "OMR",
                            LastUpdated = new DateTime(2026, 2, 16, 13, 15, 34, 473, DateTimeKind.Utc).AddTicks(9970),
                            Rate = 0.3845m
                        });
                });

            modelBuilder.Entity("alina_backend.app.finance.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("alina_backend.app.finance.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvailableBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EscrowBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PendingWithdrawal")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("alina_backend.app.finance.WithdrawalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankDetails")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WithdrawalRequests");
                });

            modelBuilder.Entity("alina_backend.app.fraud.FraudFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("SeverityScore")
                        .HasColumnType("numeric");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FraudFlags");
                });

            modelBuilder.Entity("alina_backend.app.legal.LegalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LegalDocuments");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c24a5be-48df-4564-b47d-6b7fa2165943"),
                            CreatedAt = new DateTime(2026, 2, 16, 13, 15, 34, 474, DateTimeKind.Utc).AddTicks(440),
                            Icon = "brush",
                            Name = "Graphics & Design",
                            NameAr = "الجرافيك والتصميم"
                        },
                        new
                        {
                            Id = new Guid("88384db2-0bbf-44f8-b887-621dd28c8b7d"),
                            CreatedAt = new DateTime(2026, 2, 16, 13, 15, 34, 474, DateTimeKind.Utc).AddTicks(450),
                            Icon = "code",
                            Name = "Programming & Tech",
                            NameAr = "البرمجة والتكنولوجيا"
                        },
                        new
                        {
                            Id = new Guid("8d93de44-ea35-4bbc-b9a1-2a687d3388c1"),
                            CreatedAt = new DateTime(2026, 2, 16, 13, 15, 34, 474, DateTimeKind.Utc).AddTicks(450),
                            Icon = "pen",
                            Name = "Writing & Translation",
                            NameAr = "الكتابة والترجمة"
                        },
                        new
                        {
                            Id = new Guid("71eb5645-212c-4f11-b78a-a0276d2ea17e"),
                            CreatedAt = new DateTime(2026, 2, 16, 13, 15, 34, 474, DateTimeKind.Utc).AddTicks(450),
                            Icon = "video",
                            Name = "Video & Animation",
                            NameAr = "الفيديو والأنيميشن"
                        },
                        new
                        {
                            Id = new Guid("62396ff6-dd3b-46bf-b9ae-120ceccdbaf2"),
                            CreatedAt = new DateTime(2026, 2, 16, 13, 15, 34, 474, DateTimeKind.Utc).AddTicks(460),
                            Icon = "home",
                            Name = "Home Services",
                            NameAr = "خدمات المنزل"
                        },
                        new
                        {
                            Id = new Guid("9ef9356b-83a5-4356-b1a5-70e1fe10a3b9"),
                            CreatedAt = new DateTime(2026, 2, 16, 13, 15, 34, 474, DateTimeKind.Utc).AddTicks(460),
                            Name = "Logo Design",
                            NameAr = "تصميم الشعارات",
                            ParentId = new Guid("2c24a5be-48df-4564-b47d-6b7fa2165943")
                        },
                        new
                        {
                            Id = new Guid("263bcf0a-72db-4cf5-802c-54a88422a015"),
                            CreatedAt = new DateTime(2026, 2, 16, 13, 15, 34, 474, DateTimeKind.Utc).AddTicks(470),
                            Name = "Web Design",
                            NameAr = "تصميم المواقع",
                            ParentId = new Guid("2c24a5be-48df-4564-b47d-6b7fa2165943")
                        },
                        new
                        {
                            Id = new Guid("56ca8261-f754-4a51-81e6-8a61710a3c79"),
                            CreatedAt = new DateTime(2026, 2, 16, 13, 15, 34, 474, DateTimeKind.Utc).AddTicks(470),
                            Name = "Brand Identity",
                            NameAr = "هوية العلامة التجارية",
                            ParentId = new Guid("2c24a5be-48df-4564-b47d-6b7fa2165943")
                        },
                        new
                        {
                            Id = new Guid("356dcd5d-edf2-4ca7-97dd-c75e965a5464"),
                            CreatedAt = new DateTime(2026, 2, 16, 13, 15, 34, 474, DateTimeKind.Utc).AddTicks(480),
                            Name = "Web Development",
                            NameAr = "تطوير المواقع",
                            ParentId = new Guid("88384db2-0bbf-44f8-b887-621dd28c8b7d")
                        },
                        new
                        {
                            Id = new Guid("d4eafd38-bd26-4946-800d-7c9f9693c9cb"),
                            CreatedAt = new DateTime(2026, 2, 16, 13, 15, 34, 474, DateTimeKind.Utc).AddTicks(490),
                            Name = "Mobile Apps",
                            NameAr = "تطبيقات الجوال",
                            ParentId = new Guid("88384db2-0bbf-44f8-b887-621dd28c8b7d")
                        },
                        new
                        {
                            Id = new Guid("a3b77d05-5e81-483b-91ae-2bed9cc0a54d"),
                            CreatedAt = new DateTime(2026, 2, 16, 13, 15, 34, 474, DateTimeKind.Utc).AddTicks(500),
                            Name = "AI Services",
                            NameAr = "خدمات الذكاء الاصطناعي",
                            ParentId = new Guid("88384db2-0bbf-44f8-b887-621dd28c8b7d")
                        },
                        new
                        {
                            Id = new Guid("9633fb93-81f0-452c-bd3b-2979a4626213"),
                            CreatedAt = new DateTime(2026, 2, 16, 13, 15, 34, 474, DateTimeKind.Utc).AddTicks(500),
                            Name = "Cleaning",
                            NameAr = "التنظيف",
                            ParentId = new Guid("62396ff6-dd3b-46bf-b9ae-120ceccdbaf2")
                        },
                        new
                        {
                            Id = new Guid("149c280e-cd4d-433d-a5c1-2849566f4e15"),
                            CreatedAt = new DateTime(2026, 2, 16, 13, 15, 34, 474, DateTimeKind.Utc).AddTicks(510),
                            Name = "Handyman",
                            NameAr = "أعمال الصيانة",
                            ParentId = new Guid("62396ff6-dd3b-46bf-b9ae-120ceccdbaf2")
                        },
                        new
                        {
                            Id = new Guid("669aace8-2b55-4d05-8232-83eb1b721951"),
                            CreatedAt = new DateTime(2026, 2, 16, 13, 15, 34, 474, DateTimeKind.Utc).AddTicks(520),
                            Name = "Moving",
                            NameAr = "نقل الأثاث",
                            ParentId = new Guid("62396ff6-dd3b-46bf-b9ae-120ceccdbaf2")
                        },
                        new
                        {
                            Id = new Guid("e2387fab-a208-4d0f-bfcb-0d574d08d860"),
                            CreatedAt = new DateTime(2026, 2, 16, 13, 15, 34, 474, DateTimeKind.Utc).AddTicks(520),
                            Name = "Gardening",
                            NameAr = "تنسيق الحدائق",
                            ParentId = new Guid("62396ff6-dd3b-46bf-b9ae-120ceccdbaf2")
                        });
                });

            modelBuilder.Entity("alina_backend.app.marketplace.CustomOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attachments")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("DeliveryTimeInDays")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("CustomOffers");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GigId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GigId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GigId1");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Gig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeliveryTimeInDays")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MainImage")
                        .HasColumnType("text");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.ToTable("Gigs");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("TaskerId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<List<string>>("AttachmentUrls")
                        .HasColumnType("text[]");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CommissionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryMessage")
                        .HasColumnType("text");

                    b.Property<Guid?>("GigId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PlatformFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PlatformFeePercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<decimal?>("SellerAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("GigId");

                    b.HasIndex("OfferId")
                        .IsUnique();

                    b.HasIndex("SellerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeliveryTimeInDays")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GigId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GigId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("RevieweeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("RevieweeId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.SearchAnalytics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FirstSearchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSearchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SearchCount")
                        .HasColumnType("integer");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SearchAnalytics");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.UserTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedTaskerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<Guid>("PosterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTaskerId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PosterId");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("alina_backend.app.media.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("GigId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GigId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("UserTaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserTaskId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.HasIndex("GigId1");

                    b.HasIndex("OwnerId");

                    b.HasIndex("UserTaskId");

                    b.HasIndex("UserTaskId1");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("alina_backend.app.messaging.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("alina_backend.app.notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("alina_backend.app.notifications.UserNotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MarketingEmails")
                        .HasColumnType("boolean");

                    b.Property<bool>("MessageNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("OfferNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("OrderUpdates")
                        .HasColumnType("boolean");

                    b.Property<bool>("PushEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotificationSettings");
                });

            modelBuilder.Entity("alina_backend.app.orders.Revision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attachments")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequesterId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RequesterId1")
                        .HasColumnType("uuid");

                    b.Property<string>("ResolutionAttachments")
                        .HasColumnType("text");

                    b.Property<string>("ResolutionMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId1");

                    b.ToTable("Revisions");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7794c13-7539-4019-8473-982e9dd16097"),
                            Code = "en",
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("33ac6195-0990-4e8d-bbce-29ea6ca35a75"),
                            Code = "ar",
                            Name = "Arabic"
                        },
                        new
                        {
                            Id = new Guid("7e7248ef-f9a8-4427-8adc-3b85073326d0"),
                            Code = "es",
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = new Guid("97257379-f220-407a-8be2-5054e8419f77"),
                            Code = "fr",
                            Name = "French"
                        },
                        new
                        {
                            Id = new Guid("68fa71be-4645-4610-9f54-44f3cb89b37d"),
                            Code = "de",
                            Name = "German"
                        },
                        new
                        {
                            Id = new Guid("c59f2d3b-eff9-4835-a66c-7ef4bf094df8"),
                            Code = "zh",
                            Name = "Chinese"
                        },
                        new
                        {
                            Id = new Guid("de705a6d-2f13-458d-82e2-2ccd43a2f329"),
                            Code = "ja",
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = new Guid("f5c82e93-1d9a-40c8-90f1-213270ce0b7d"),
                            Code = "pt",
                            Name = "Portuguese"
                        },
                        new
                        {
                            Id = new Guid("72b7810a-ee98-4b10-a352-a5dd01cf8a42"),
                            Code = "ru",
                            Name = "Russian"
                        },
                        new
                        {
                            Id = new Guid("a85b7a89-418e-458e-a634-34a425c5774b"),
                            Code = "hi",
                            Name = "Hindi"
                        });
                });

            modelBuilder.Entity("alina_backend.app.profiles.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GithubUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastDeliveryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PreferredCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("ProfileCompletionPercentage")
                        .HasColumnType("integer");

                    b.Property<int?>("ResponseTimeHours")
                        .HasColumnType("integer");

                    b.Property<int>("SellerLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Tagline")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TwitterUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("alina_backend.app.profiles.ProfileLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProficiencyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileLanguages");
                });

            modelBuilder.Entity("alina_backend.app.profiles.ProfileSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProfileSkills");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b37f7fe0-7c4b-494c-b1e9-a97af8f79816"),
                            CategoryName = "Programming",
                            Name = "React"
                        },
                        new
                        {
                            Id = new Guid("812e7be1-5c59-43f9-a767-1b1a16735c57"),
                            CategoryName = "Programming",
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = new Guid("f7504825-d58d-4ddb-8d45-c0b9ba76858a"),
                            CategoryName = "Programming",
                            Name = "Python"
                        },
                        new
                        {
                            Id = new Guid("2a7e3051-61eb-4be9-80dc-30a819c07aab"),
                            CategoryName = "Programming",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("7bc68723-ca4f-451a-94c4-ce97296f1b14"),
                            CategoryName = "Programming",
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = new Guid("674a3274-08a2-4274-b14a-ea9be59e34a3"),
                            CategoryName = "Programming",
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("de3f0b4d-71c0-40b6-a4da-d4e054752894"),
                            CategoryName = "Programming",
                            Name = "Java"
                        },
                        new
                        {
                            Id = new Guid("b20d4152-c653-4e47-a3fe-61d5d66e32bc"),
                            CategoryName = "Programming",
                            Name = "Flutter"
                        },
                        new
                        {
                            Id = new Guid("4c968f5c-6bac-4d07-ac6c-4b028b662cb1"),
                            CategoryName = "Programming",
                            Name = "Swift"
                        },
                        new
                        {
                            Id = new Guid("43d55dd5-911a-489f-82bf-956d1b587c7d"),
                            CategoryName = "Programming",
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = new Guid("293d071e-feb5-406f-8dd9-10493f189cb5"),
                            CategoryName = "Design",
                            Name = "UI/UX Design"
                        },
                        new
                        {
                            Id = new Guid("da19045d-1a50-4c9c-b8c8-d3a7f58353eb"),
                            CategoryName = "Design",
                            Name = "Figma"
                        },
                        new
                        {
                            Id = new Guid("ecd0af05-6629-472e-92a9-4530895b56ba"),
                            CategoryName = "Design",
                            Name = "Adobe Photoshop"
                        },
                        new
                        {
                            Id = new Guid("922e2cbb-5590-4e07-9983-80e7b05a7f94"),
                            CategoryName = "Design",
                            Name = "Adobe Illustrator"
                        },
                        new
                        {
                            Id = new Guid("1d8b8668-aea7-4902-9163-c02a66e811b3"),
                            CategoryName = "Design",
                            Name = "Graphic Design"
                        },
                        new
                        {
                            Id = new Guid("36154402-fdae-4ba8-bfd0-0c28775935c4"),
                            CategoryName = "Design",
                            Name = "Logo Design"
                        },
                        new
                        {
                            Id = new Guid("c7fbd7e0-b3a8-4a59-8376-1801ffb631fd"),
                            CategoryName = "Design",
                            Name = "3D Modeling"
                        },
                        new
                        {
                            Id = new Guid("75a7cf47-1a35-4833-a766-13ded328b5ad"),
                            CategoryName = "Marketing",
                            Name = "SEO"
                        },
                        new
                        {
                            Id = new Guid("61701521-83d4-4b50-a27e-1b08c488f27d"),
                            CategoryName = "Marketing",
                            Name = "Social Media Marketing"
                        },
                        new
                        {
                            Id = new Guid("040eb669-7ec3-4af2-a36e-81e032ce4c24"),
                            CategoryName = "Marketing",
                            Name = "Content Writing"
                        },
                        new
                        {
                            Id = new Guid("29bbf5e9-b3e4-4493-9193-1b8897c471da"),
                            CategoryName = "Marketing",
                            Name = "Email Marketing"
                        },
                        new
                        {
                            Id = new Guid("d0e089c8-aeda-4686-b6f5-61279d352185"),
                            CategoryName = "Marketing",
                            Name = "Digital Marketing"
                        },
                        new
                        {
                            Id = new Guid("7d4dc021-01f8-4f72-ab35-e85ce023d1e4"),
                            CategoryName = "Video & Animation",
                            Name = "Video Editing"
                        },
                        new
                        {
                            Id = new Guid("e4c50e60-22ad-4914-be82-7a937aeace9f"),
                            CategoryName = "Video & Animation",
                            Name = "After Effects"
                        },
                        new
                        {
                            Id = new Guid("d9f7b615-ddcd-4539-9d8f-aba1f8098f08"),
                            CategoryName = "Video & Animation",
                            Name = "Animation"
                        },
                        new
                        {
                            Id = new Guid("43b231ed-a2f2-4c5e-8c30-ccde856d9df7"),
                            CategoryName = "Writing",
                            Name = "Copywriting"
                        },
                        new
                        {
                            Id = new Guid("1fd3d71a-b2dd-4b40-87e5-77194205fc14"),
                            CategoryName = "Writing",
                            Name = "Technical Writing"
                        },
                        new
                        {
                            Id = new Guid("e46ebf19-eb18-4755-bd16-d3f20ae10c85"),
                            CategoryName = "Writing",
                            Name = "Translation"
                        },
                        new
                        {
                            Id = new Guid("abb43eaa-c04d-43fb-b9d4-19ec609ab248"),
                            CategoryName = "Business",
                            Name = "Data Analysis"
                        },
                        new
                        {
                            Id = new Guid("659dfe69-279e-4de6-b03f-ed9501031247"),
                            CategoryName = "Business",
                            Name = "Business Consulting"
                        });
                });

            modelBuilder.Entity("alina_backend.app.support.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("alina_backend.app.users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("alina_backend.app.users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.Goal", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.GoalProgress", b =>
                {
                    b.HasOne("alina_backend.app.dashboard.Goal", "Goal")
                        .WithMany("ProgressEntries")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("alina_backend.app.disputes.Dispute", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("alina_backend.app.finance.Transaction", b =>
                {
                    b.HasOne("alina_backend.app.finance.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("alina_backend.app.finance.Wallet", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Profile")
                        .WithOne()
                        .HasForeignKey("alina_backend.app.finance.Wallet", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("alina_backend.app.finance.WithdrawalRequest", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.fraud.FraudFlag", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Category", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Category", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.CustomOffer", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.users.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Favorite", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Gig", "Gig")
                        .WithMany()
                        .HasForeignKey("GigId1");

                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Gig", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Category", "Category")
                        .WithMany("Gigs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Offer", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.UserTask", "Task")
                        .WithMany("Offers")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Tasker")
                        .WithMany()
                        .HasForeignKey("TaskerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("Tasker");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Order", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("alina_backend.app.marketplace.Gig", "Gig")
                        .WithMany()
                        .HasForeignKey("GigId");

                    b.HasOne("alina_backend.app.marketplace.Offer", "Offer")
                        .WithOne()
                        .HasForeignKey("alina_backend.app.marketplace.Order", "OfferId");

                    b.HasOne("alina_backend.app.profiles.Profile", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Gig");

                    b.Navigation("Offer");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Package", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Gig", "Gig")
                        .WithMany("Packages")
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Review", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Gig", "Gig")
                        .WithMany("Reviews")
                        .HasForeignKey("GigId");

                    b.HasOne("alina_backend.app.marketplace.Order", "Order")
                        .WithOne()
                        .HasForeignKey("alina_backend.app.marketplace.Review", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Reviewee")
                        .WithMany()
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");

                    b.Navigation("Order");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.SearchAnalytics", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.UserTask", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "AssignedTasker")
                        .WithMany()
                        .HasForeignKey("AssignedTaskerId");

                    b.HasOne("alina_backend.app.marketplace.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Poster")
                        .WithMany()
                        .HasForeignKey("PosterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTasker");

                    b.Navigation("Category");

                    b.Navigation("Poster");
                });

            modelBuilder.Entity("alina_backend.app.media.Media", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Gig", null)
                        .WithMany()
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("alina_backend.app.marketplace.Gig", null)
                        .WithMany("Gallery")
                        .HasForeignKey("GigId1");

                    b.HasOne("alina_backend.app.profiles.Profile", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.HasOne("alina_backend.app.marketplace.UserTask", null)
                        .WithMany()
                        .HasForeignKey("UserTaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("alina_backend.app.marketplace.UserTask", null)
                        .WithMany("Attachments")
                        .HasForeignKey("UserTaskId1");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("alina_backend.app.messaging.Message", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("alina_backend.app.notifications.Notification", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.notifications.UserNotificationSettings", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.orders.Revision", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId1");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Profile", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithOne()
                        .HasForeignKey("alina_backend.app.profiles.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.profiles.ProfileLanguage", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Language", "Language")
                        .WithMany("ProfileLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Profile")
                        .WithMany("ProfileLanguages")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("alina_backend.app.profiles.ProfileSkill", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Profile")
                        .WithMany("ProfileSkills")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Skill", "Skill")
                        .WithMany("ProfileSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("alina_backend.app.support.SupportTicket", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.users.RefreshToken", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.Goal", b =>
                {
                    b.Navigation("ProgressEntries");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Category", b =>
                {
                    b.Navigation("Gigs");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Gig", b =>
                {
                    b.Navigation("Gallery");

                    b.Navigation("Packages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.UserTask", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Language", b =>
                {
                    b.Navigation("ProfileLanguages");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Profile", b =>
                {
                    b.Navigation("ProfileLanguages");

                    b.Navigation("ProfileSkills");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Skill", b =>
                {
                    b.Navigation("ProfileSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
