// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using alina_backend;

#nullable disable

namespace alina_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260217080526_UpdateCustomOfferAttachments")]
    partial class UpdateCustomOfferAttachments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("alina_backend.app.dashboard.AchievementBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("GoalType")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("AchievementBadges");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AchievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AchievementBadge")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAchieved")
                        .HasColumnType("boolean");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ProgressPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.GoalProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("GoalProgress");
                });

            modelBuilder.Entity("alina_backend.app.disputes.Dispute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OpenedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("Resolution")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ResolutionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Disputes");
                });

            modelBuilder.Entity("alina_backend.app.finance.CurrencyRate", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Code");

                    b.ToTable("CurrencyRates");

                    b.HasData(
                        new
                        {
                            Code = "USD",
                            LastUpdated = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3180),
                            Rate = 1.0000m
                        },
                        new
                        {
                            Code = "SAR",
                            LastUpdated = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3190),
                            Rate = 3.7500m
                        },
                        new
                        {
                            Code = "AED",
                            LastUpdated = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3190),
                            Rate = 3.6725m
                        },
                        new
                        {
                            Code = "JOD",
                            LastUpdated = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3190),
                            Rate = 0.7090m
                        },
                        new
                        {
                            Code = "KWD",
                            LastUpdated = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3190),
                            Rate = 0.3070m
                        },
                        new
                        {
                            Code = "BHD",
                            LastUpdated = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3190),
                            Rate = 0.3760m
                        },
                        new
                        {
                            Code = "OMR",
                            LastUpdated = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3190),
                            Rate = 0.3845m
                        });
                });

            modelBuilder.Entity("alina_backend.app.finance.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("alina_backend.app.finance.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvailableBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EscrowBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PendingWithdrawal")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("alina_backend.app.finance.WithdrawalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankDetails")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WithdrawalRequests");
                });

            modelBuilder.Entity("alina_backend.app.fraud.FraudFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("SeverityScore")
                        .HasColumnType("numeric");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FraudFlags");
                });

            modelBuilder.Entity("alina_backend.app.legal.LegalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LegalDocuments");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8541b9f-ff51-4647-958d-67ce311ad0ff"),
                            CreatedAt = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3740),
                            Icon = "brush",
                            Name = "Graphics & Design",
                            NameAr = "الجرافيك والتصميم"
                        },
                        new
                        {
                            Id = new Guid("d285d3bc-cf1b-4ff4-81a8-f021f5875373"),
                            CreatedAt = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3740),
                            Icon = "code",
                            Name = "Programming & Tech",
                            NameAr = "البرمجة والتكنولوجيا"
                        },
                        new
                        {
                            Id = new Guid("de077909-8a5f-4ab1-979a-ff460ae3e487"),
                            CreatedAt = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3750),
                            Icon = "pen",
                            Name = "Writing & Translation",
                            NameAr = "الكتابة والترجمة"
                        },
                        new
                        {
                            Id = new Guid("87013797-7602-4939-80f7-a1e057bd31fd"),
                            CreatedAt = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3750),
                            Icon = "video",
                            Name = "Video & Animation",
                            NameAr = "الفيديو والأنيميشن"
                        },
                        new
                        {
                            Id = new Guid("51a0a5bc-0601-4cd1-b3a2-d3b2d7354c8a"),
                            CreatedAt = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3750),
                            Icon = "home",
                            Name = "Home Services",
                            NameAr = "خدمات المنزل"
                        },
                        new
                        {
                            Id = new Guid("fd222e6a-8fd1-489a-8e1a-bb975fa6012d"),
                            CreatedAt = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3760),
                            Name = "Logo Design",
                            NameAr = "تصميم الشعارات",
                            ParentId = new Guid("b8541b9f-ff51-4647-958d-67ce311ad0ff")
                        },
                        new
                        {
                            Id = new Guid("863abcdb-7567-476d-ad30-cd792d746c65"),
                            CreatedAt = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3770),
                            Name = "Web Design",
                            NameAr = "تصميم المواقع",
                            ParentId = new Guid("b8541b9f-ff51-4647-958d-67ce311ad0ff")
                        },
                        new
                        {
                            Id = new Guid("8f692628-c815-4cab-b2c9-f4e6ee4dd8f9"),
                            CreatedAt = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3770),
                            Name = "Brand Identity",
                            NameAr = "هوية العلامة التجارية",
                            ParentId = new Guid("b8541b9f-ff51-4647-958d-67ce311ad0ff")
                        },
                        new
                        {
                            Id = new Guid("d34a1c80-6595-4669-8625-b86d12515145"),
                            CreatedAt = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3780),
                            Name = "Web Development",
                            NameAr = "تطوير المواقع",
                            ParentId = new Guid("d285d3bc-cf1b-4ff4-81a8-f021f5875373")
                        },
                        new
                        {
                            Id = new Guid("b4cff0e6-2be8-4fe2-9af4-b33fcf24d81f"),
                            CreatedAt = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3790),
                            Name = "Mobile Apps",
                            NameAr = "تطبيقات الجوال",
                            ParentId = new Guid("d285d3bc-cf1b-4ff4-81a8-f021f5875373")
                        },
                        new
                        {
                            Id = new Guid("827fb46c-4944-402f-be28-e23319506970"),
                            CreatedAt = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3790),
                            Name = "AI Services",
                            NameAr = "خدمات الذكاء الاصطناعي",
                            ParentId = new Guid("d285d3bc-cf1b-4ff4-81a8-f021f5875373")
                        },
                        new
                        {
                            Id = new Guid("409cc8ff-ea73-4285-80ca-bab598dacdea"),
                            CreatedAt = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3800),
                            Name = "Cleaning",
                            NameAr = "التنظيف",
                            ParentId = new Guid("51a0a5bc-0601-4cd1-b3a2-d3b2d7354c8a")
                        },
                        new
                        {
                            Id = new Guid("43463f64-f77a-4ab3-86ee-dc4cfdca58f3"),
                            CreatedAt = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3810),
                            Name = "Handyman",
                            NameAr = "أعمال الصيانة",
                            ParentId = new Guid("51a0a5bc-0601-4cd1-b3a2-d3b2d7354c8a")
                        },
                        new
                        {
                            Id = new Guid("15b5bd57-d715-425b-ac79-919e7d20b060"),
                            CreatedAt = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3810),
                            Name = "Moving",
                            NameAr = "نقل الأثاث",
                            ParentId = new Guid("51a0a5bc-0601-4cd1-b3a2-d3b2d7354c8a")
                        },
                        new
                        {
                            Id = new Guid("30d27215-6a86-433f-bc8c-2562ba5fc626"),
                            CreatedAt = new DateTime(2026, 2, 17, 8, 5, 25, 896, DateTimeKind.Utc).AddTicks(3820),
                            Name = "Gardening",
                            NameAr = "تنسيق الحدائق",
                            ParentId = new Guid("51a0a5bc-0601-4cd1-b3a2-d3b2d7354c8a")
                        });
                });

            modelBuilder.Entity("alina_backend.app.marketplace.CustomOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attachments")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("DeliveryTimeInDays")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("CustomOffers");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GigId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GigId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GigId1");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Gig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeliveryTimeInDays")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MainImage")
                        .HasColumnType("text");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.ToTable("Gigs");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("TaskerId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<List<string>>("AttachmentUrls")
                        .HasColumnType("text[]");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CommissionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryMessage")
                        .HasColumnType("text");

                    b.Property<Guid?>("GigId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PlatformFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PlatformFeePercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<decimal?>("SellerAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("GigId");

                    b.HasIndex("OfferId")
                        .IsUnique();

                    b.HasIndex("SellerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeliveryTimeInDays")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GigId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GigId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("RevieweeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("RevieweeId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.SearchAnalytics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FirstSearchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSearchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SearchCount")
                        .HasColumnType("integer");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SearchAnalytics");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.UserTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedTaskerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<Guid>("PosterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTaskerId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PosterId");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("alina_backend.app.media.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomOfferId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("GigId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GigId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("UserTaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserTaskId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.HasIndex("GigId1");

                    b.HasIndex("OwnerId");

                    b.HasIndex("UserTaskId");

                    b.HasIndex("UserTaskId1");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("alina_backend.app.messaging.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("alina_backend.app.notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("alina_backend.app.notifications.UserNotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MarketingEmails")
                        .HasColumnType("boolean");

                    b.Property<bool>("MessageNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("OfferNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("OrderUpdates")
                        .HasColumnType("boolean");

                    b.Property<bool>("PushEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotificationSettings");
                });

            modelBuilder.Entity("alina_backend.app.orders.Revision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attachments")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequesterId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RequesterId1")
                        .HasColumnType("uuid");

                    b.Property<string>("ResolutionAttachments")
                        .HasColumnType("text");

                    b.Property<string>("ResolutionMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId1");

                    b.ToTable("Revisions");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0593158-1e45-4c63-bd36-8c9997fc8903"),
                            Code = "en",
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("1c052f91-dac6-48ce-b1b3-b4b4f3548b99"),
                            Code = "ar",
                            Name = "Arabic"
                        },
                        new
                        {
                            Id = new Guid("c7f93ef2-46a9-4000-b487-bd091e2cc08b"),
                            Code = "es",
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = new Guid("e67abf33-f09b-4202-9b3f-9ab084cb83c0"),
                            Code = "fr",
                            Name = "French"
                        },
                        new
                        {
                            Id = new Guid("85d3dd0e-1eb6-4df0-9f88-d6653556596b"),
                            Code = "de",
                            Name = "German"
                        },
                        new
                        {
                            Id = new Guid("2d253003-c6e1-49d8-9e40-04b161bb446b"),
                            Code = "zh",
                            Name = "Chinese"
                        },
                        new
                        {
                            Id = new Guid("39e6216b-9bde-4f36-9bc3-4b0895090cb9"),
                            Code = "ja",
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = new Guid("733cda4f-bedc-4ce1-95b9-43daff090297"),
                            Code = "pt",
                            Name = "Portuguese"
                        },
                        new
                        {
                            Id = new Guid("21820034-fc00-4f48-8bc6-c2e8821801c9"),
                            Code = "ru",
                            Name = "Russian"
                        },
                        new
                        {
                            Id = new Guid("053505e7-caa1-4d35-91db-b7dc14bf955d"),
                            Code = "hi",
                            Name = "Hindi"
                        });
                });

            modelBuilder.Entity("alina_backend.app.profiles.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GithubUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastDeliveryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PreferredCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("ProfileCompletionPercentage")
                        .HasColumnType("integer");

                    b.Property<int?>("ResponseTimeHours")
                        .HasColumnType("integer");

                    b.Property<int>("SellerLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Tagline")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TwitterUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("alina_backend.app.profiles.ProfileLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProficiencyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileLanguages");
                });

            modelBuilder.Entity("alina_backend.app.profiles.ProfileSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProfileSkills");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("17a65e40-9bba-4899-9daf-21da5e801e3d"),
                            CategoryName = "Programming",
                            Name = "React"
                        },
                        new
                        {
                            Id = new Guid("9d316d31-47e5-4c92-918f-87926dbeeeb2"),
                            CategoryName = "Programming",
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = new Guid("9cd93b38-221f-457b-a5b8-ca43c2ddc451"),
                            CategoryName = "Programming",
                            Name = "Python"
                        },
                        new
                        {
                            Id = new Guid("1e017769-4c7e-40ed-b7f8-7fa5b8b0e134"),
                            CategoryName = "Programming",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("0c018b5b-3286-4533-a0dd-9664226bc6db"),
                            CategoryName = "Programming",
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = new Guid("7375e22f-0475-4edf-b901-dff9f8ab829d"),
                            CategoryName = "Programming",
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("a168514f-2a24-4cc7-942c-e5e62ce18614"),
                            CategoryName = "Programming",
                            Name = "Java"
                        },
                        new
                        {
                            Id = new Guid("5c1e3119-7ac6-4e9b-9147-84d414d62500"),
                            CategoryName = "Programming",
                            Name = "Flutter"
                        },
                        new
                        {
                            Id = new Guid("bbc962dd-abf7-4fb5-9f5e-1a75fc6727bb"),
                            CategoryName = "Programming",
                            Name = "Swift"
                        },
                        new
                        {
                            Id = new Guid("d0e393c7-23de-44ea-9084-9f9091816fad"),
                            CategoryName = "Programming",
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = new Guid("c429373d-f469-43a2-a071-514799d283e9"),
                            CategoryName = "Design",
                            Name = "UI/UX Design"
                        },
                        new
                        {
                            Id = new Guid("b498c526-8ac7-49e9-903e-e97184bda7e2"),
                            CategoryName = "Design",
                            Name = "Figma"
                        },
                        new
                        {
                            Id = new Guid("32897b17-18d2-4ca8-a2fc-7ddf94768e82"),
                            CategoryName = "Design",
                            Name = "Adobe Photoshop"
                        },
                        new
                        {
                            Id = new Guid("2392b60b-76db-459c-bb3a-e003fbc19c15"),
                            CategoryName = "Design",
                            Name = "Adobe Illustrator"
                        },
                        new
                        {
                            Id = new Guid("fa47d805-0a5c-447d-a001-e270b4cd035d"),
                            CategoryName = "Design",
                            Name = "Graphic Design"
                        },
                        new
                        {
                            Id = new Guid("917e75cf-4363-4e72-91b4-7a78b6999f1b"),
                            CategoryName = "Design",
                            Name = "Logo Design"
                        },
                        new
                        {
                            Id = new Guid("73fb92ae-9a66-431b-a6f5-5b6cbee4f569"),
                            CategoryName = "Design",
                            Name = "3D Modeling"
                        },
                        new
                        {
                            Id = new Guid("04f2f7c9-578d-4392-bb6b-9e58a3947038"),
                            CategoryName = "Marketing",
                            Name = "SEO"
                        },
                        new
                        {
                            Id = new Guid("646c2db4-f9e6-43b0-a902-49a30a344e92"),
                            CategoryName = "Marketing",
                            Name = "Social Media Marketing"
                        },
                        new
                        {
                            Id = new Guid("9f2e1b75-6e7b-4a75-91d4-47b69ebb2e77"),
                            CategoryName = "Marketing",
                            Name = "Content Writing"
                        },
                        new
                        {
                            Id = new Guid("0c900d02-e569-4623-a16a-494113fc7da9"),
                            CategoryName = "Marketing",
                            Name = "Email Marketing"
                        },
                        new
                        {
                            Id = new Guid("7c650c25-df0b-4a23-a8d0-52199bf53004"),
                            CategoryName = "Marketing",
                            Name = "Digital Marketing"
                        },
                        new
                        {
                            Id = new Guid("d3cfc84e-0623-48f0-b6f4-75a546fb88f8"),
                            CategoryName = "Video & Animation",
                            Name = "Video Editing"
                        },
                        new
                        {
                            Id = new Guid("58be5bdb-cedc-406e-a2c5-3dc7c7fbec53"),
                            CategoryName = "Video & Animation",
                            Name = "After Effects"
                        },
                        new
                        {
                            Id = new Guid("d717e887-a886-4919-961e-f81a88ac0c96"),
                            CategoryName = "Video & Animation",
                            Name = "Animation"
                        },
                        new
                        {
                            Id = new Guid("d6ee631d-cd93-4425-b156-6f20b8c4cf43"),
                            CategoryName = "Writing",
                            Name = "Copywriting"
                        },
                        new
                        {
                            Id = new Guid("81f835bc-32dc-4675-a370-8c95f5141739"),
                            CategoryName = "Writing",
                            Name = "Technical Writing"
                        },
                        new
                        {
                            Id = new Guid("4ca0678a-7c15-470e-aeb4-46ace6c0000c"),
                            CategoryName = "Writing",
                            Name = "Translation"
                        },
                        new
                        {
                            Id = new Guid("2a5297b4-a977-4e04-8e04-fb897320e7f1"),
                            CategoryName = "Business",
                            Name = "Data Analysis"
                        },
                        new
                        {
                            Id = new Guid("0b17ba05-4a8f-4241-be7d-b88c8f80ca0c"),
                            CategoryName = "Business",
                            Name = "Business Consulting"
                        });
                });

            modelBuilder.Entity("alina_backend.app.support.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("alina_backend.app.users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("alina_backend.app.users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.Goal", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.GoalProgress", b =>
                {
                    b.HasOne("alina_backend.app.dashboard.Goal", "Goal")
                        .WithMany("ProgressEntries")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("alina_backend.app.disputes.Dispute", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("alina_backend.app.finance.Transaction", b =>
                {
                    b.HasOne("alina_backend.app.finance.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("alina_backend.app.finance.Wallet", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Profile")
                        .WithOne()
                        .HasForeignKey("alina_backend.app.finance.Wallet", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("alina_backend.app.finance.WithdrawalRequest", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.fraud.FraudFlag", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Category", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Category", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.CustomOffer", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.users.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Favorite", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Gig", "Gig")
                        .WithMany()
                        .HasForeignKey("GigId1");

                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Gig", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Category", "Category")
                        .WithMany("Gigs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Offer", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.UserTask", "Task")
                        .WithMany("Offers")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Tasker")
                        .WithMany()
                        .HasForeignKey("TaskerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("Tasker");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Order", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("alina_backend.app.marketplace.Gig", "Gig")
                        .WithMany()
                        .HasForeignKey("GigId");

                    b.HasOne("alina_backend.app.marketplace.Offer", "Offer")
                        .WithOne()
                        .HasForeignKey("alina_backend.app.marketplace.Order", "OfferId");

                    b.HasOne("alina_backend.app.profiles.Profile", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Gig");

                    b.Navigation("Offer");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Package", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Gig", "Gig")
                        .WithMany("Packages")
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Review", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Gig", "Gig")
                        .WithMany("Reviews")
                        .HasForeignKey("GigId");

                    b.HasOne("alina_backend.app.marketplace.Order", "Order")
                        .WithOne()
                        .HasForeignKey("alina_backend.app.marketplace.Review", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Reviewee")
                        .WithMany()
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");

                    b.Navigation("Order");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.SearchAnalytics", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.UserTask", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "AssignedTasker")
                        .WithMany()
                        .HasForeignKey("AssignedTaskerId");

                    b.HasOne("alina_backend.app.marketplace.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Poster")
                        .WithMany()
                        .HasForeignKey("PosterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTasker");

                    b.Navigation("Category");

                    b.Navigation("Poster");
                });

            modelBuilder.Entity("alina_backend.app.media.Media", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Gig", null)
                        .WithMany()
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("alina_backend.app.marketplace.Gig", null)
                        .WithMany("Gallery")
                        .HasForeignKey("GigId1");

                    b.HasOne("alina_backend.app.profiles.Profile", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.HasOne("alina_backend.app.marketplace.UserTask", null)
                        .WithMany()
                        .HasForeignKey("UserTaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("alina_backend.app.marketplace.UserTask", null)
                        .WithMany("Attachments")
                        .HasForeignKey("UserTaskId1");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("alina_backend.app.messaging.Message", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("alina_backend.app.notifications.Notification", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.notifications.UserNotificationSettings", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.orders.Revision", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId1");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Profile", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithOne()
                        .HasForeignKey("alina_backend.app.profiles.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.profiles.ProfileLanguage", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Language", "Language")
                        .WithMany("ProfileLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Profile")
                        .WithMany("ProfileLanguages")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("alina_backend.app.profiles.ProfileSkill", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Profile")
                        .WithMany("ProfileSkills")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Skill", "Skill")
                        .WithMany("ProfileSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("alina_backend.app.support.SupportTicket", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.users.RefreshToken", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.Goal", b =>
                {
                    b.Navigation("ProgressEntries");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Category", b =>
                {
                    b.Navigation("Gigs");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Gig", b =>
                {
                    b.Navigation("Gallery");

                    b.Navigation("Packages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.UserTask", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Language", b =>
                {
                    b.Navigation("ProfileLanguages");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Profile", b =>
                {
                    b.Navigation("ProfileLanguages");

                    b.Navigation("ProfileSkills");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Skill", b =>
                {
                    b.Navigation("ProfileSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
