// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using alina_backend;

#nullable disable

namespace alina_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260215120305_AddUserIdAndCreatedAtToWallet")]
    partial class AddUserIdAndCreatedAtToWallet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("alina_backend.app.dashboard.AchievementBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("GoalType")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("AchievementBadges");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AchievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AchievementBadge")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAchieved")
                        .HasColumnType("boolean");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ProgressPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.GoalProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("GoalProgress");
                });

            modelBuilder.Entity("alina_backend.app.disputes.Dispute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OpenedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("Resolution")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ResolutionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Disputes");
                });

            modelBuilder.Entity("alina_backend.app.finance.CurrencyRate", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Code");

                    b.ToTable("CurrencyRates");

                    b.HasData(
                        new
                        {
                            Code = "USD",
                            LastUpdated = new DateTime(2026, 2, 15, 12, 3, 5, 92, DateTimeKind.Utc).AddTicks(9370),
                            Rate = 1.0000m
                        },
                        new
                        {
                            Code = "SAR",
                            LastUpdated = new DateTime(2026, 2, 15, 12, 3, 5, 92, DateTimeKind.Utc).AddTicks(9370),
                            Rate = 3.7500m
                        },
                        new
                        {
                            Code = "AED",
                            LastUpdated = new DateTime(2026, 2, 15, 12, 3, 5, 92, DateTimeKind.Utc).AddTicks(9370),
                            Rate = 3.6725m
                        },
                        new
                        {
                            Code = "JOD",
                            LastUpdated = new DateTime(2026, 2, 15, 12, 3, 5, 92, DateTimeKind.Utc).AddTicks(9370),
                            Rate = 0.7090m
                        },
                        new
                        {
                            Code = "KWD",
                            LastUpdated = new DateTime(2026, 2, 15, 12, 3, 5, 92, DateTimeKind.Utc).AddTicks(9380),
                            Rate = 0.3070m
                        },
                        new
                        {
                            Code = "BHD",
                            LastUpdated = new DateTime(2026, 2, 15, 12, 3, 5, 92, DateTimeKind.Utc).AddTicks(9380),
                            Rate = 0.3760m
                        },
                        new
                        {
                            Code = "OMR",
                            LastUpdated = new DateTime(2026, 2, 15, 12, 3, 5, 92, DateTimeKind.Utc).AddTicks(9380),
                            Rate = 0.3845m
                        });
                });

            modelBuilder.Entity("alina_backend.app.finance.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("alina_backend.app.finance.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvailableBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EscrowBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("alina_backend.app.finance.WithdrawalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankDetails")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WithdrawalRequests");
                });

            modelBuilder.Entity("alina_backend.app.fraud.FraudFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("SeverityScore")
                        .HasColumnType("numeric");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FraudFlags");
                });

            modelBuilder.Entity("alina_backend.app.legal.LegalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LegalDocuments");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3eded8ff-5181-4e98-8c57-8e708ba7d168"),
                            CreatedAt = new DateTime(2026, 2, 15, 12, 3, 5, 93, DateTimeKind.Utc),
                            Icon = "brush",
                            Name = "Graphics & Design",
                            NameAr = "الجرافيك والتصميم"
                        },
                        new
                        {
                            Id = new Guid("3d389326-3136-4124-9603-3e60b9cee518"),
                            CreatedAt = new DateTime(2026, 2, 15, 12, 3, 5, 93, DateTimeKind.Utc),
                            Icon = "code",
                            Name = "Programming & Tech",
                            NameAr = "البرمجة والتكنولوجيا"
                        },
                        new
                        {
                            Id = new Guid("73b798b8-d3d1-4dab-882e-e9da86d3d3b5"),
                            CreatedAt = new DateTime(2026, 2, 15, 12, 3, 5, 93, DateTimeKind.Utc).AddTicks(10),
                            Icon = "pen",
                            Name = "Writing & Translation",
                            NameAr = "الكتابة والترجمة"
                        },
                        new
                        {
                            Id = new Guid("15cd7934-59a8-41e6-b90c-a08905f96750"),
                            CreatedAt = new DateTime(2026, 2, 15, 12, 3, 5, 93, DateTimeKind.Utc).AddTicks(10),
                            Icon = "video",
                            Name = "Video & Animation",
                            NameAr = "الفيديو والأنيميشن"
                        },
                        new
                        {
                            Id = new Guid("7fc6bb9a-2aa8-4b90-a645-e2a2955e5c98"),
                            CreatedAt = new DateTime(2026, 2, 15, 12, 3, 5, 93, DateTimeKind.Utc).AddTicks(10),
                            Icon = "home",
                            Name = "Home Services",
                            NameAr = "خدمات المنزل"
                        },
                        new
                        {
                            Id = new Guid("18678614-b29d-44c7-be73-bdaf764116b2"),
                            CreatedAt = new DateTime(2026, 2, 15, 12, 3, 5, 93, DateTimeKind.Utc).AddTicks(20),
                            Name = "Logo Design",
                            NameAr = "تصميم الشعارات",
                            ParentId = new Guid("3eded8ff-5181-4e98-8c57-8e708ba7d168")
                        },
                        new
                        {
                            Id = new Guid("962b5459-16c4-4a52-8c86-e91ab327a993"),
                            CreatedAt = new DateTime(2026, 2, 15, 12, 3, 5, 93, DateTimeKind.Utc).AddTicks(20),
                            Name = "Web Design",
                            NameAr = "تصميم المواقع",
                            ParentId = new Guid("3eded8ff-5181-4e98-8c57-8e708ba7d168")
                        },
                        new
                        {
                            Id = new Guid("261ba990-2e9a-4a8c-8c57-933ac0d6bd5d"),
                            CreatedAt = new DateTime(2026, 2, 15, 12, 3, 5, 93, DateTimeKind.Utc).AddTicks(30),
                            Name = "Brand Identity",
                            NameAr = "هوية العلامة التجارية",
                            ParentId = new Guid("3eded8ff-5181-4e98-8c57-8e708ba7d168")
                        },
                        new
                        {
                            Id = new Guid("a323738e-2c4b-49f1-8463-14e85d861d8a"),
                            CreatedAt = new DateTime(2026, 2, 15, 12, 3, 5, 93, DateTimeKind.Utc).AddTicks(40),
                            Name = "Web Development",
                            NameAr = "تطوير المواقع",
                            ParentId = new Guid("3d389326-3136-4124-9603-3e60b9cee518")
                        },
                        new
                        {
                            Id = new Guid("ccb9add0-d01f-4105-bfe9-c11b6f214181"),
                            CreatedAt = new DateTime(2026, 2, 15, 12, 3, 5, 93, DateTimeKind.Utc).AddTicks(40),
                            Name = "Mobile Apps",
                            NameAr = "تطبيقات الجوال",
                            ParentId = new Guid("3d389326-3136-4124-9603-3e60b9cee518")
                        },
                        new
                        {
                            Id = new Guid("eb37f8b6-a695-4079-9304-22374a83da76"),
                            CreatedAt = new DateTime(2026, 2, 15, 12, 3, 5, 93, DateTimeKind.Utc).AddTicks(50),
                            Name = "AI Services",
                            NameAr = "خدمات الذكاء الاصطناعي",
                            ParentId = new Guid("3d389326-3136-4124-9603-3e60b9cee518")
                        },
                        new
                        {
                            Id = new Guid("1930a9cb-041c-4ff7-97e6-c5d06d0059e3"),
                            CreatedAt = new DateTime(2026, 2, 15, 12, 3, 5, 93, DateTimeKind.Utc).AddTicks(60),
                            Name = "Cleaning",
                            NameAr = "التنظيف",
                            ParentId = new Guid("7fc6bb9a-2aa8-4b90-a645-e2a2955e5c98")
                        },
                        new
                        {
                            Id = new Guid("413c95d6-abdb-4f3d-b975-6cdbab30fb73"),
                            CreatedAt = new DateTime(2026, 2, 15, 12, 3, 5, 93, DateTimeKind.Utc).AddTicks(70),
                            Name = "Handyman",
                            NameAr = "أعمال الصيانة",
                            ParentId = new Guid("7fc6bb9a-2aa8-4b90-a645-e2a2955e5c98")
                        },
                        new
                        {
                            Id = new Guid("d8a9922b-f163-4909-af7e-5f3ce8c326d2"),
                            CreatedAt = new DateTime(2026, 2, 15, 12, 3, 5, 93, DateTimeKind.Utc).AddTicks(70),
                            Name = "Moving",
                            NameAr = "نقل الأثاث",
                            ParentId = new Guid("7fc6bb9a-2aa8-4b90-a645-e2a2955e5c98")
                        },
                        new
                        {
                            Id = new Guid("cc03ebc2-dfa3-46f1-b0d7-98aef9344890"),
                            CreatedAt = new DateTime(2026, 2, 15, 12, 3, 5, 93, DateTimeKind.Utc).AddTicks(80),
                            Name = "Gardening",
                            NameAr = "تنسيق الحدائق",
                            ParentId = new Guid("7fc6bb9a-2aa8-4b90-a645-e2a2955e5c98")
                        });
                });

            modelBuilder.Entity("alina_backend.app.marketplace.CustomOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attachments")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("DeliveryTimeInDays")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("CustomOffers");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GigId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GigId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GigId1");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Gig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeliveryTimeInDays")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MainImage")
                        .HasColumnType("text");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.ToTable("Gigs");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("TaskerId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CommissionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GigId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PlatformFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PlatformFeePercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<decimal?>("SellerAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("GigId");

                    b.HasIndex("OfferId")
                        .IsUnique();

                    b.HasIndex("SellerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeliveryTimeInDays")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GigId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GigId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("RevieweeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("RevieweeId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.UserTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedTaskerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<Guid>("PosterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTaskerId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PosterId");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("alina_backend.app.media.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("GigId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GigId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("UserTaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserTaskId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.HasIndex("GigId1");

                    b.HasIndex("OwnerId");

                    b.HasIndex("UserTaskId");

                    b.HasIndex("UserTaskId1");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("alina_backend.app.messaging.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("alina_backend.app.notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("alina_backend.app.notifications.UserNotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MarketingEmails")
                        .HasColumnType("boolean");

                    b.Property<bool>("MessageNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("OfferNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("OrderUpdates")
                        .HasColumnType("boolean");

                    b.Property<bool>("PushEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotificationSettings");
                });

            modelBuilder.Entity("alina_backend.app.orders.Revision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attachments")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequesterId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RequesterId1")
                        .HasColumnType("uuid");

                    b.Property<string>("ResolutionAttachments")
                        .HasColumnType("text");

                    b.Property<string>("ResolutionMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId1");

                    b.ToTable("Revisions");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a4ff96bb-54db-4cef-aa3a-ca9247f740e8"),
                            Code = "en",
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("42bd78c7-7902-4025-bd0f-841996e04ce5"),
                            Code = "ar",
                            Name = "Arabic"
                        },
                        new
                        {
                            Id = new Guid("9beef803-29ab-46db-bbd3-2a834d047a56"),
                            Code = "es",
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = new Guid("871b533a-8783-4ef5-a21b-7e43f2330905"),
                            Code = "fr",
                            Name = "French"
                        },
                        new
                        {
                            Id = new Guid("09a29d95-fde5-45d6-8773-929ec35e8f20"),
                            Code = "de",
                            Name = "German"
                        },
                        new
                        {
                            Id = new Guid("3770601a-ac97-4662-a580-7fefce1c3700"),
                            Code = "zh",
                            Name = "Chinese"
                        },
                        new
                        {
                            Id = new Guid("1a8a5079-0aba-41a9-8e28-36b8f72c9cc8"),
                            Code = "ja",
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = new Guid("f3add990-2b24-4829-a9dd-d8f644437bdd"),
                            Code = "pt",
                            Name = "Portuguese"
                        },
                        new
                        {
                            Id = new Guid("1736a0a6-bdb3-48dd-b067-14fe0f9ddf26"),
                            Code = "ru",
                            Name = "Russian"
                        },
                        new
                        {
                            Id = new Guid("82b0aa5b-ac3c-403f-bf4e-a7d7a30bde88"),
                            Code = "hi",
                            Name = "Hindi"
                        });
                });

            modelBuilder.Entity("alina_backend.app.profiles.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GithubUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastDeliveryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PreferredCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("ProfileCompletionPercentage")
                        .HasColumnType("integer");

                    b.Property<int?>("ResponseTimeHours")
                        .HasColumnType("integer");

                    b.Property<string>("Tagline")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TwitterUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("alina_backend.app.profiles.ProfileLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProficiencyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileLanguages");
                });

            modelBuilder.Entity("alina_backend.app.profiles.ProfileSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProfileSkills");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("847e6c0e-2fee-4b07-8200-3f756e961e6c"),
                            CategoryName = "Programming",
                            Name = "React"
                        },
                        new
                        {
                            Id = new Guid("2ae390ed-738b-4080-b0da-7dfd2d386d88"),
                            CategoryName = "Programming",
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = new Guid("08f7a1b1-6d9c-4dfd-b8fa-4478640cafc7"),
                            CategoryName = "Programming",
                            Name = "Python"
                        },
                        new
                        {
                            Id = new Guid("f1dbb88b-16fe-4d57-80e4-e90dee0cdd49"),
                            CategoryName = "Programming",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("9336a944-7f6d-42dd-9d0d-133d181b929a"),
                            CategoryName = "Programming",
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = new Guid("145d1dfd-a738-41d0-ae47-0a1b9e0d0b81"),
                            CategoryName = "Programming",
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("9506bcec-a605-4783-8846-24ff1d1d3381"),
                            CategoryName = "Programming",
                            Name = "Java"
                        },
                        new
                        {
                            Id = new Guid("297c09c9-9de0-4971-b3bd-ca8cf82a168e"),
                            CategoryName = "Programming",
                            Name = "Flutter"
                        },
                        new
                        {
                            Id = new Guid("399e66b9-b166-477f-9e3f-fb0285636b07"),
                            CategoryName = "Programming",
                            Name = "Swift"
                        },
                        new
                        {
                            Id = new Guid("eeb8ecba-17f6-4a55-8879-befe97110c09"),
                            CategoryName = "Programming",
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = new Guid("6d5b827b-2f79-4daf-bca0-e064a829bea9"),
                            CategoryName = "Design",
                            Name = "UI/UX Design"
                        },
                        new
                        {
                            Id = new Guid("ce94b33c-8ffd-426b-b4fd-e70d82379e5c"),
                            CategoryName = "Design",
                            Name = "Figma"
                        },
                        new
                        {
                            Id = new Guid("c54bd846-a8ed-43a0-bf2c-cb776e9afb15"),
                            CategoryName = "Design",
                            Name = "Adobe Photoshop"
                        },
                        new
                        {
                            Id = new Guid("1870f32d-838f-483c-8471-1f9fd0beff82"),
                            CategoryName = "Design",
                            Name = "Adobe Illustrator"
                        },
                        new
                        {
                            Id = new Guid("60eb0921-6a9e-47d0-bcf9-84b322784a83"),
                            CategoryName = "Design",
                            Name = "Graphic Design"
                        },
                        new
                        {
                            Id = new Guid("d64e5734-7559-4f92-a81d-49e7cae910f3"),
                            CategoryName = "Design",
                            Name = "Logo Design"
                        },
                        new
                        {
                            Id = new Guid("cde8b508-8613-4658-b486-58c56fc525e8"),
                            CategoryName = "Design",
                            Name = "3D Modeling"
                        },
                        new
                        {
                            Id = new Guid("d3132b5e-f703-43d5-86c9-51fcd4e4bd7e"),
                            CategoryName = "Marketing",
                            Name = "SEO"
                        },
                        new
                        {
                            Id = new Guid("8297086b-2e67-4b1d-95ed-48bc0c68d6dc"),
                            CategoryName = "Marketing",
                            Name = "Social Media Marketing"
                        },
                        new
                        {
                            Id = new Guid("c9329ff5-3ef4-445d-a108-14bd0ea838be"),
                            CategoryName = "Marketing",
                            Name = "Content Writing"
                        },
                        new
                        {
                            Id = new Guid("55c62ffa-2c45-403f-bab5-ad53b578741b"),
                            CategoryName = "Marketing",
                            Name = "Email Marketing"
                        },
                        new
                        {
                            Id = new Guid("eccd7971-56d4-4660-8685-340f2b3cf78a"),
                            CategoryName = "Marketing",
                            Name = "Digital Marketing"
                        },
                        new
                        {
                            Id = new Guid("f2e1fd06-937d-4510-b92d-d6e7edf6bedd"),
                            CategoryName = "Video & Animation",
                            Name = "Video Editing"
                        },
                        new
                        {
                            Id = new Guid("bbd0fde9-ea1f-426e-9446-b5c42cea1fe8"),
                            CategoryName = "Video & Animation",
                            Name = "After Effects"
                        },
                        new
                        {
                            Id = new Guid("91b26704-7e62-47cb-8eca-4e40821058bf"),
                            CategoryName = "Video & Animation",
                            Name = "Animation"
                        },
                        new
                        {
                            Id = new Guid("7bbfee3f-e853-4b20-9b0d-be0c968dbbde"),
                            CategoryName = "Writing",
                            Name = "Copywriting"
                        },
                        new
                        {
                            Id = new Guid("f4c29478-c6c2-41f0-a3c6-a715dda1379b"),
                            CategoryName = "Writing",
                            Name = "Technical Writing"
                        },
                        new
                        {
                            Id = new Guid("19c1f32e-2dfc-400f-8d07-d3e67ac14222"),
                            CategoryName = "Writing",
                            Name = "Translation"
                        },
                        new
                        {
                            Id = new Guid("bfee105a-988d-4c9c-998d-f582838015fc"),
                            CategoryName = "Business",
                            Name = "Data Analysis"
                        },
                        new
                        {
                            Id = new Guid("3505827e-4216-4e14-b3e6-a68774ab67f6"),
                            CategoryName = "Business",
                            Name = "Business Consulting"
                        });
                });

            modelBuilder.Entity("alina_backend.app.support.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("alina_backend.app.users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("alina_backend.app.users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.Goal", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.GoalProgress", b =>
                {
                    b.HasOne("alina_backend.app.dashboard.Goal", "Goal")
                        .WithMany("ProgressEntries")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("alina_backend.app.disputes.Dispute", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("alina_backend.app.finance.Transaction", b =>
                {
                    b.HasOne("alina_backend.app.finance.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("alina_backend.app.finance.Wallet", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Profile")
                        .WithOne()
                        .HasForeignKey("alina_backend.app.finance.Wallet", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("alina_backend.app.finance.WithdrawalRequest", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.fraud.FraudFlag", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Category", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Category", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.CustomOffer", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.users.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Favorite", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Gig", "Gig")
                        .WithMany()
                        .HasForeignKey("GigId1");

                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Gig", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Category", "Category")
                        .WithMany("Gigs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Offer", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.UserTask", "Task")
                        .WithMany("Offers")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Tasker")
                        .WithMany()
                        .HasForeignKey("TaskerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("Tasker");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Order", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("alina_backend.app.marketplace.Gig", "Gig")
                        .WithMany()
                        .HasForeignKey("GigId");

                    b.HasOne("alina_backend.app.marketplace.Offer", "Offer")
                        .WithOne()
                        .HasForeignKey("alina_backend.app.marketplace.Order", "OfferId");

                    b.HasOne("alina_backend.app.profiles.Profile", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Gig");

                    b.Navigation("Offer");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Package", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Gig", "Gig")
                        .WithMany("Packages")
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Review", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Gig", "Gig")
                        .WithMany("Reviews")
                        .HasForeignKey("GigId");

                    b.HasOne("alina_backend.app.marketplace.Order", "Order")
                        .WithOne()
                        .HasForeignKey("alina_backend.app.marketplace.Review", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Reviewee")
                        .WithMany()
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");

                    b.Navigation("Order");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.UserTask", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "AssignedTasker")
                        .WithMany()
                        .HasForeignKey("AssignedTaskerId");

                    b.HasOne("alina_backend.app.marketplace.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Poster")
                        .WithMany()
                        .HasForeignKey("PosterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTasker");

                    b.Navigation("Category");

                    b.Navigation("Poster");
                });

            modelBuilder.Entity("alina_backend.app.media.Media", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Gig", null)
                        .WithMany()
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("alina_backend.app.marketplace.Gig", null)
                        .WithMany("Gallery")
                        .HasForeignKey("GigId1");

                    b.HasOne("alina_backend.app.profiles.Profile", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.HasOne("alina_backend.app.marketplace.UserTask", null)
                        .WithMany()
                        .HasForeignKey("UserTaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("alina_backend.app.marketplace.UserTask", null)
                        .WithMany("Attachments")
                        .HasForeignKey("UserTaskId1");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("alina_backend.app.messaging.Message", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("alina_backend.app.notifications.Notification", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.notifications.UserNotificationSettings", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.orders.Revision", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId1");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Profile", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithOne()
                        .HasForeignKey("alina_backend.app.profiles.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.profiles.ProfileLanguage", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Language", "Language")
                        .WithMany("ProfileLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Profile")
                        .WithMany("ProfileLanguages")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("alina_backend.app.profiles.ProfileSkill", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Profile")
                        .WithMany("ProfileSkills")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Skill", "Skill")
                        .WithMany("ProfileSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("alina_backend.app.support.SupportTicket", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.users.RefreshToken", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.Goal", b =>
                {
                    b.Navigation("ProgressEntries");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Category", b =>
                {
                    b.Navigation("Gigs");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Gig", b =>
                {
                    b.Navigation("Gallery");

                    b.Navigation("Packages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.UserTask", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Language", b =>
                {
                    b.Navigation("ProfileLanguages");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Profile", b =>
                {
                    b.Navigation("ProfileLanguages");

                    b.Navigation("ProfileSkills");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Skill", b =>
                {
                    b.Navigation("ProfileSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
