// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using alina_backend;

#nullable disable

namespace alina_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260216082134_AddProductionWithdrawalSystem")]
    partial class AddProductionWithdrawalSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("alina_backend.app.dashboard.AchievementBadge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("GoalType")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("AchievementBadges");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AchievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AchievementBadge")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAchieved")
                        .HasColumnType("boolean");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ProgressPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.GoalProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("GoalProgress");
                });

            modelBuilder.Entity("alina_backend.app.disputes.Dispute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OpenedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("Resolution")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ResolutionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Disputes");
                });

            modelBuilder.Entity("alina_backend.app.finance.CurrencyRate", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Code");

                    b.ToTable("CurrencyRates");

                    b.HasData(
                        new
                        {
                            Code = "USD",
                            LastUpdated = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(2680),
                            Rate = 1.0000m
                        },
                        new
                        {
                            Code = "SAR",
                            LastUpdated = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(2680),
                            Rate = 3.7500m
                        },
                        new
                        {
                            Code = "AED",
                            LastUpdated = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(2690),
                            Rate = 3.6725m
                        },
                        new
                        {
                            Code = "JOD",
                            LastUpdated = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(2690),
                            Rate = 0.7090m
                        },
                        new
                        {
                            Code = "KWD",
                            LastUpdated = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(2690),
                            Rate = 0.3070m
                        },
                        new
                        {
                            Code = "BHD",
                            LastUpdated = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(2690),
                            Rate = 0.3760m
                        },
                        new
                        {
                            Code = "OMR",
                            LastUpdated = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(2690),
                            Rate = 0.3845m
                        });
                });

            modelBuilder.Entity("alina_backend.app.finance.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("alina_backend.app.finance.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AvailableBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EscrowBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PendingWithdrawal")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("alina_backend.app.finance.WithdrawalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankDetails")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WithdrawalRequests");
                });

            modelBuilder.Entity("alina_backend.app.fraud.FraudFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("SeverityScore")
                        .HasColumnType("numeric");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FraudFlags");
                });

            modelBuilder.Entity("alina_backend.app.legal.LegalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LegalDocuments");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e6e916e4-51e4-4976-813f-c655c0439292"),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(3490),
                            Icon = "brush",
                            Name = "Graphics & Design",
                            NameAr = "الجرافيك والتصميم"
                        },
                        new
                        {
                            Id = new Guid("2ccafa1a-8f52-433d-a783-5d1e881a48ab"),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(3500),
                            Icon = "code",
                            Name = "Programming & Tech",
                            NameAr = "البرمجة والتكنولوجيا"
                        },
                        new
                        {
                            Id = new Guid("18de8269-6512-4863-acea-6e956f348f98"),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(3510),
                            Icon = "pen",
                            Name = "Writing & Translation",
                            NameAr = "الكتابة والترجمة"
                        },
                        new
                        {
                            Id = new Guid("3d9145b6-db6b-486e-bbba-4d00067f5233"),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(3510),
                            Icon = "video",
                            Name = "Video & Animation",
                            NameAr = "الفيديو والأنيميشن"
                        },
                        new
                        {
                            Id = new Guid("acf3f1ee-6371-481b-b1b6-b12219fc659b"),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(3510),
                            Icon = "home",
                            Name = "Home Services",
                            NameAr = "خدمات المنزل"
                        },
                        new
                        {
                            Id = new Guid("4e12f5e8-7012-479d-ba83-74b605bf9637"),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(3520),
                            Name = "Logo Design",
                            NameAr = "تصميم الشعارات",
                            ParentId = new Guid("e6e916e4-51e4-4976-813f-c655c0439292")
                        },
                        new
                        {
                            Id = new Guid("ac51c32d-24d3-4f25-8125-5189b8df3b05"),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(3530),
                            Name = "Web Design",
                            NameAr = "تصميم المواقع",
                            ParentId = new Guid("e6e916e4-51e4-4976-813f-c655c0439292")
                        },
                        new
                        {
                            Id = new Guid("0c87a00a-25cb-4fd0-84a0-4df84d863a39"),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(3530),
                            Name = "Brand Identity",
                            NameAr = "هوية العلامة التجارية",
                            ParentId = new Guid("e6e916e4-51e4-4976-813f-c655c0439292")
                        },
                        new
                        {
                            Id = new Guid("23b8425f-16e4-463c-a6cd-185894c82a88"),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(3540),
                            Name = "Web Development",
                            NameAr = "تطوير المواقع",
                            ParentId = new Guid("2ccafa1a-8f52-433d-a783-5d1e881a48ab")
                        },
                        new
                        {
                            Id = new Guid("33e54cae-a3d8-4902-bc10-c98513fb6d8a"),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(3550),
                            Name = "Mobile Apps",
                            NameAr = "تطبيقات الجوال",
                            ParentId = new Guid("2ccafa1a-8f52-433d-a783-5d1e881a48ab")
                        },
                        new
                        {
                            Id = new Guid("0f9523bd-363b-4e8d-be2e-5f7969abfc9a"),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(3560),
                            Name = "AI Services",
                            NameAr = "خدمات الذكاء الاصطناعي",
                            ParentId = new Guid("2ccafa1a-8f52-433d-a783-5d1e881a48ab")
                        },
                        new
                        {
                            Id = new Guid("c611810c-b3ac-41e8-afd1-7351d75e51c9"),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(3570),
                            Name = "Cleaning",
                            NameAr = "التنظيف",
                            ParentId = new Guid("acf3f1ee-6371-481b-b1b6-b12219fc659b")
                        },
                        new
                        {
                            Id = new Guid("bca1912f-8c07-454d-af21-c5301656a0fb"),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(3570),
                            Name = "Handyman",
                            NameAr = "أعمال الصيانة",
                            ParentId = new Guid("acf3f1ee-6371-481b-b1b6-b12219fc659b")
                        },
                        new
                        {
                            Id = new Guid("42a9b552-9620-46b9-aefe-aff244029b25"),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(3580),
                            Name = "Moving",
                            NameAr = "نقل الأثاث",
                            ParentId = new Guid("acf3f1ee-6371-481b-b1b6-b12219fc659b")
                        },
                        new
                        {
                            Id = new Guid("20de0003-d65d-4527-b4c5-c152392adbf5"),
                            CreatedAt = new DateTime(2026, 2, 16, 8, 21, 34, 469, DateTimeKind.Utc).AddTicks(3590),
                            Name = "Gardening",
                            NameAr = "تنسيق الحدائق",
                            ParentId = new Guid("acf3f1ee-6371-481b-b1b6-b12219fc659b")
                        });
                });

            modelBuilder.Entity("alina_backend.app.marketplace.CustomOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attachments")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("DeliveryTimeInDays")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Features")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("text");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("CustomOffers");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GigId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GigId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GigId1");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Gig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeliveryTimeInDays")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MainImage")
                        .HasColumnType("text");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.ToTable("Gigs");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("TaskerId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CommissionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GigId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PlatformFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PlatformFeePercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<decimal?>("SellerAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("GigId");

                    b.HasIndex("OfferId")
                        .IsUnique();

                    b.HasIndex("SellerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DeliveryTimeInDays")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GigId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GigId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("RevieweeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("RevieweeId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.UserTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedTaskerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<Guid>("PosterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTaskerId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PosterId");

                    b.ToTable("UserTasks");
                });

            modelBuilder.Entity("alina_backend.app.media.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("GigId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GigId1")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("UserTaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserTaskId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GigId");

                    b.HasIndex("GigId1");

                    b.HasIndex("OwnerId");

                    b.HasIndex("UserTaskId");

                    b.HasIndex("UserTaskId1");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("alina_backend.app.messaging.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("alina_backend.app.notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("alina_backend.app.notifications.UserNotificationSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MarketingEmails")
                        .HasColumnType("boolean");

                    b.Property<bool>("MessageNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("OfferNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("OrderUpdates")
                        .HasColumnType("boolean");

                    b.Property<bool>("PushEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotificationSettings");
                });

            modelBuilder.Entity("alina_backend.app.orders.Revision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attachments")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequesterId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RequesterId1")
                        .HasColumnType("uuid");

                    b.Property<string>("ResolutionAttachments")
                        .HasColumnType("text");

                    b.Property<string>("ResolutionMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId1");

                    b.ToTable("Revisions");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("73c00f55-de92-42f2-9990-ffae1fc01a76"),
                            Code = "en",
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("bf39cf35-bd4a-413d-be2b-91904cfe0aa9"),
                            Code = "ar",
                            Name = "Arabic"
                        },
                        new
                        {
                            Id = new Guid("9e8a5739-0d81-4167-bbae-0f64515f07b6"),
                            Code = "es",
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = new Guid("1447823f-e46a-44e6-862a-adae915fba6a"),
                            Code = "fr",
                            Name = "French"
                        },
                        new
                        {
                            Id = new Guid("923cc2ab-c11a-4d37-906e-8e3607bb8528"),
                            Code = "de",
                            Name = "German"
                        },
                        new
                        {
                            Id = new Guid("646da794-ef6a-4a1c-8912-00210a502150"),
                            Code = "zh",
                            Name = "Chinese"
                        },
                        new
                        {
                            Id = new Guid("4d018b57-795c-47d8-bbc9-334d55a27c65"),
                            Code = "ja",
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = new Guid("1413e2e5-3f94-406b-8532-e8864ba91938"),
                            Code = "pt",
                            Name = "Portuguese"
                        },
                        new
                        {
                            Id = new Guid("5d4cbe35-b48d-4081-a9b4-bcd01790981f"),
                            Code = "ru",
                            Name = "Russian"
                        },
                        new
                        {
                            Id = new Guid("64e46d4b-21ee-413f-b45e-68825aeea8c1"),
                            Code = "hi",
                            Name = "Hindi"
                        });
                });

            modelBuilder.Entity("alina_backend.app.profiles.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GithubUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastDeliveryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PreferredCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("ProfileCompletionPercentage")
                        .HasColumnType("integer");

                    b.Property<int?>("ResponseTimeHours")
                        .HasColumnType("integer");

                    b.Property<int>("SellerLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Tagline")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TwitterUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("alina_backend.app.profiles.ProfileLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProficiencyLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileLanguages");
                });

            modelBuilder.Entity("alina_backend.app.profiles.ProfileSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProfileSkills");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1c54224d-6035-4094-a20b-5c25543f4ebf"),
                            CategoryName = "Programming",
                            Name = "React"
                        },
                        new
                        {
                            Id = new Guid("0562a5cb-61ae-45bc-9a6d-c7a402bde347"),
                            CategoryName = "Programming",
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = new Guid("b3c22354-1495-4aca-86cb-2da54a9ada86"),
                            CategoryName = "Programming",
                            Name = "Python"
                        },
                        new
                        {
                            Id = new Guid("3302e939-3fb5-42b8-a40f-43d47919df28"),
                            CategoryName = "Programming",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("fe4263c2-6e3c-405e-a5fd-a57f60bfb5ac"),
                            CategoryName = "Programming",
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = new Guid("478fa79b-3d0d-4686-87f2-463ea61d3fec"),
                            CategoryName = "Programming",
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("d2e368fe-609a-45c6-8471-87bc1339a85c"),
                            CategoryName = "Programming",
                            Name = "Java"
                        },
                        new
                        {
                            Id = new Guid("f9b59233-3353-4c63-baf1-379c371de6a1"),
                            CategoryName = "Programming",
                            Name = "Flutter"
                        },
                        new
                        {
                            Id = new Guid("2fa00585-6f26-4585-a4b1-85016475f676"),
                            CategoryName = "Programming",
                            Name = "Swift"
                        },
                        new
                        {
                            Id = new Guid("20f11881-72c0-4aba-a87a-5c688a74312f"),
                            CategoryName = "Programming",
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = new Guid("e8ba6a35-a7ba-4af0-8b39-d2b8067d20aa"),
                            CategoryName = "Design",
                            Name = "UI/UX Design"
                        },
                        new
                        {
                            Id = new Guid("b4c591e8-3a95-4889-996b-83a84befe805"),
                            CategoryName = "Design",
                            Name = "Figma"
                        },
                        new
                        {
                            Id = new Guid("2ad30878-0139-4281-a353-e063b7f59360"),
                            CategoryName = "Design",
                            Name = "Adobe Photoshop"
                        },
                        new
                        {
                            Id = new Guid("81afe858-a4ac-44a0-a6d2-8843de08f458"),
                            CategoryName = "Design",
                            Name = "Adobe Illustrator"
                        },
                        new
                        {
                            Id = new Guid("286ea299-34ac-4fb9-90f0-3ea18abd466e"),
                            CategoryName = "Design",
                            Name = "Graphic Design"
                        },
                        new
                        {
                            Id = new Guid("a46f5008-7d65-42fb-b6c4-5abd601f198b"),
                            CategoryName = "Design",
                            Name = "Logo Design"
                        },
                        new
                        {
                            Id = new Guid("77396ad1-563c-4262-a6b0-9df26d3df5c3"),
                            CategoryName = "Design",
                            Name = "3D Modeling"
                        },
                        new
                        {
                            Id = new Guid("d022eb62-ad47-43d4-b715-5d462a486f36"),
                            CategoryName = "Marketing",
                            Name = "SEO"
                        },
                        new
                        {
                            Id = new Guid("29752820-7a0f-44f4-bf73-ecb41c4cd06a"),
                            CategoryName = "Marketing",
                            Name = "Social Media Marketing"
                        },
                        new
                        {
                            Id = new Guid("38b07a29-7e14-4f94-b00a-23e62b810c6d"),
                            CategoryName = "Marketing",
                            Name = "Content Writing"
                        },
                        new
                        {
                            Id = new Guid("8aac63c1-f6d3-4712-b4c3-2785653b6cbb"),
                            CategoryName = "Marketing",
                            Name = "Email Marketing"
                        },
                        new
                        {
                            Id = new Guid("32331b3e-2416-42d9-8d91-eaffdff1bb05"),
                            CategoryName = "Marketing",
                            Name = "Digital Marketing"
                        },
                        new
                        {
                            Id = new Guid("a0a86fd2-6410-42fc-87c2-c27d85656fb2"),
                            CategoryName = "Video & Animation",
                            Name = "Video Editing"
                        },
                        new
                        {
                            Id = new Guid("529cabeb-12ee-4fb4-868e-41c80b85124d"),
                            CategoryName = "Video & Animation",
                            Name = "After Effects"
                        },
                        new
                        {
                            Id = new Guid("f7372cdd-e900-4ba6-b97b-616bd85b8536"),
                            CategoryName = "Video & Animation",
                            Name = "Animation"
                        },
                        new
                        {
                            Id = new Guid("eb7df5cd-39d1-4e20-b45b-446f2affd51e"),
                            CategoryName = "Writing",
                            Name = "Copywriting"
                        },
                        new
                        {
                            Id = new Guid("37fd1fa5-c436-4dd1-a5ac-2501dd741ccf"),
                            CategoryName = "Writing",
                            Name = "Technical Writing"
                        },
                        new
                        {
                            Id = new Guid("c42483c3-afbf-4c57-a209-f17b95315786"),
                            CategoryName = "Writing",
                            Name = "Translation"
                        },
                        new
                        {
                            Id = new Guid("af37c2e7-7b0a-4b22-be20-5de74c3c005c"),
                            CategoryName = "Business",
                            Name = "Data Analysis"
                        },
                        new
                        {
                            Id = new Guid("a3b3f805-7144-48be-9a65-b62eaab62fd5"),
                            CategoryName = "Business",
                            Name = "Business Consulting"
                        });
                });

            modelBuilder.Entity("alina_backend.app.support.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("alina_backend.app.users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("alina_backend.app.users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.Goal", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.GoalProgress", b =>
                {
                    b.HasOne("alina_backend.app.dashboard.Goal", "Goal")
                        .WithMany("ProgressEntries")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("alina_backend.app.disputes.Dispute", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("alina_backend.app.finance.Transaction", b =>
                {
                    b.HasOne("alina_backend.app.finance.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("alina_backend.app.finance.Wallet", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Profile")
                        .WithOne()
                        .HasForeignKey("alina_backend.app.finance.Wallet", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("alina_backend.app.finance.WithdrawalRequest", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.fraud.FraudFlag", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Category", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Category", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.CustomOffer", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.users.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Favorite", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Gig", "Gig")
                        .WithMany()
                        .HasForeignKey("GigId1");

                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Gig", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Category", "Category")
                        .WithMany("Gigs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Offer", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.UserTask", "Task")
                        .WithMany("Offers")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Tasker")
                        .WithMany()
                        .HasForeignKey("TaskerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("Tasker");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Order", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("alina_backend.app.marketplace.Gig", "Gig")
                        .WithMany()
                        .HasForeignKey("GigId");

                    b.HasOne("alina_backend.app.marketplace.Offer", "Offer")
                        .WithOne()
                        .HasForeignKey("alina_backend.app.marketplace.Order", "OfferId");

                    b.HasOne("alina_backend.app.profiles.Profile", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("Gig");

                    b.Navigation("Offer");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Package", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Gig", "Gig")
                        .WithMany("Packages")
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Review", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Gig", "Gig")
                        .WithMany("Reviews")
                        .HasForeignKey("GigId");

                    b.HasOne("alina_backend.app.marketplace.Order", "Order")
                        .WithOne()
                        .HasForeignKey("alina_backend.app.marketplace.Review", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Reviewee")
                        .WithMany()
                        .HasForeignKey("RevieweeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");

                    b.Navigation("Order");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.UserTask", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "AssignedTasker")
                        .WithMany()
                        .HasForeignKey("AssignedTaskerId");

                    b.HasOne("alina_backend.app.marketplace.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Poster")
                        .WithMany()
                        .HasForeignKey("PosterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTasker");

                    b.Navigation("Category");

                    b.Navigation("Poster");
                });

            modelBuilder.Entity("alina_backend.app.media.Media", b =>
                {
                    b.HasOne("alina_backend.app.marketplace.Gig", null)
                        .WithMany()
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("alina_backend.app.marketplace.Gig", null)
                        .WithMany("Gallery")
                        .HasForeignKey("GigId1");

                    b.HasOne("alina_backend.app.profiles.Profile", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.HasOne("alina_backend.app.marketplace.UserTask", null)
                        .WithMany()
                        .HasForeignKey("UserTaskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("alina_backend.app.marketplace.UserTask", null)
                        .WithMany("Attachments")
                        .HasForeignKey("UserTaskId1");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("alina_backend.app.messaging.Message", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("alina_backend.app.notifications.Notification", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.notifications.UserNotificationSettings", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.orders.Revision", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId1");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Profile", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithOne()
                        .HasForeignKey("alina_backend.app.profiles.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.profiles.ProfileLanguage", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Language", "Language")
                        .WithMany("ProfileLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Profile", "Profile")
                        .WithMany("ProfileLanguages")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("alina_backend.app.profiles.ProfileSkill", b =>
                {
                    b.HasOne("alina_backend.app.profiles.Profile", "Profile")
                        .WithMany("ProfileSkills")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("alina_backend.app.profiles.Skill", "Skill")
                        .WithMany("ProfileSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("alina_backend.app.support.SupportTicket", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.users.RefreshToken", b =>
                {
                    b.HasOne("alina_backend.app.users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("alina_backend.app.dashboard.Goal", b =>
                {
                    b.Navigation("ProgressEntries");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Category", b =>
                {
                    b.Navigation("Gigs");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.Gig", b =>
                {
                    b.Navigation("Gallery");

                    b.Navigation("Packages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("alina_backend.app.marketplace.UserTask", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Language", b =>
                {
                    b.Navigation("ProfileLanguages");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Profile", b =>
                {
                    b.Navigation("ProfileLanguages");

                    b.Navigation("ProfileSkills");
                });

            modelBuilder.Entity("alina_backend.app.profiles.Skill", b =>
                {
                    b.Navigation("ProfileSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
