using Amazon.S3;
using Amazon.S3.Model;
using Amazon.S3.Transfer;

namespace alina_backend.Modules.media;

public class S3StorageService : IStorageService
{
    private readonly IAmazonS3 _s3Client;
    private readonly string _bucketName;
    private readonly string _cdnBaseUrl;

    public S3StorageService(IAmazonS3 s3Client, IConfiguration configuration)
    {
        _s3Client = s3Client;
        _bucketName = configuration["AWS:BucketName"] ?? throw new ArgumentNullException("AWS:BucketName not configured");
        _cdnBaseUrl = (configuration["AppSettings:CdnBaseUrl"] ?? throw new ArgumentNullException("AppSettings:CdnBaseUrl not configured")).TrimEnd('/');
    }

    // -------------------------------------------------------------------------
    // Public files: stored under "public/" prefix, served via CloudFront CDN.
    // URLs are permanent and clean — no expiry, fully SEO-indexable.
    // -------------------------------------------------------------------------
    public async Task<string> UploadPublicFileAsync(Stream fileStream, string fileName, string contentType, string folder)
    {
        var key = $"public/{folder}/{Guid.NewGuid()}{GetSafeExtension(contentType)}";

        var request = new PutObjectRequest
        {
            BucketName = _bucketName,
            Key = key,
            InputStream = fileStream,
            ContentType = contentType
            // No CannedACL — bucket policy allows CloudFront OAC to read public/ prefix
        };

        await _s3Client.PutObjectAsync(request);
        return key;
    }

    // -------------------------------------------------------------------------
    // Private files: stored under "private/" prefix, never accessible via CDN.
    // Served only via short-lived presigned URLs generated by the backend.
    // -------------------------------------------------------------------------
    public async Task<string> UploadPrivateFileAsync(Stream fileStream, string fileName, string contentType, string folder)
    {
        var key = $"private/{folder}/{Guid.NewGuid()}{GetSafeExtension(contentType)}";

        var request = new PutObjectRequest
        {
            BucketName = _bucketName,
            Key = key,
            InputStream = fileStream,
            ContentType = contentType
        };

        await _s3Client.PutObjectAsync(request);
        return key;
    }

    public async Task DeleteFileAsync(string keyOrUrl)
    {
        var key = keyOrUrl.StartsWith("http://") || keyOrUrl.StartsWith("https://")
            ? new Uri(keyOrUrl).AbsolutePath.TrimStart('/')
            : keyOrUrl;

        await _s3Client.DeleteObjectAsync(_bucketName, key);
    }

    /// <summary>
    /// Returns the permanent CDN URL for a public key.
    /// Example: "public/avatars/abc.jpg" → "https://media.aqlaan.cloud/public/avatars/abc.jpg"
    /// Only call this for keys under the "public/" prefix.
    /// </summary>
    public string GetPublicUrl(string key) => $"{_cdnBaseUrl}/{key}";

    /// <summary>
    /// Returns a short-lived presigned URL for a private key.
    /// Only call this for keys under the "private/" prefix.
    /// </summary>
    public Task<string> GetPresignedUrlAsync(string key, int expiryMinutes = 60)
    {
        var request = new GetPreSignedUrlRequest
        {
            BucketName = _bucketName,
            Key = key,
            Expires = DateTime.UtcNow.AddMinutes(expiryMinutes),
            Verb = HttpVerb.GET
        };

        return Task.FromResult(_s3Client.GetPreSignedURL(request));
    }

    private static string GetSafeExtension(string contentType) => contentType switch
    {
        "image/jpeg"        => ".jpg",
        "image/png"         => ".png",
        "image/gif"         => ".gif",
        "image/webp"        => ".webp",
        "image/svg+xml"     => ".svg",
        "application/pdf"   => ".pdf",
        "video/mp4"         => ".mp4",
        _                   => string.Empty
    };
}
